package com.multitenanterp.leave;
import com.multitenanterp.platform.tenant.TenantContext;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.web.server.ResponseStatusException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;
import static org.assertj.core.api.Assertions.*;

class LeaveServiceIntegrationTest {
 private JdbcClient db;private LeaveService service;private UUID tenantA,tenantB,employeeA,typeA;
 @BeforeEach void setup(){tenantA=UUID.randomUUID();tenantB=UUID.randomUUID();employeeA=UUID.randomUUID();JdbcDataSource ds=new JdbcDataSource();ds.setURL("jdbc:h2:mem:"+UUID.randomUUID()+";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");db=JdbcClient.create(ds);schema();db.sql("INSERT INTO tenant VALUES(?),(?)").params(tenantA,tenantB).update();db.sql("INSERT INTO employment VALUES(?,?),(?,?)").params(employeeA,tenantA,UUID.randomUUID(),tenantB).update();service=new LeaveService(db);TenantContext.set(tenantA);typeA=service.saveType(null,type("CL")).id();db.sql("INSERT INTO leave_balance(id,tenant_id,employment_id,leave_type_id,leave_year,opening_balance,accrued,adjusted,used) VALUES(?,?,?,?,?,?,?,?,?)").params(UUID.randomUUID(),tenantA,employeeA,typeA,2026,new BigDecimal("10"),BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO).update();}
 @AfterEach void clear(){TenantContext.clear();}
 @Test void requestApprovalConsumesBalance(){LeaveRequest request=service.request(new CreateLeaveRequest(employeeA,typeA,LocalDate.of(2026,9,15),LocalDate.of(2026,9,16),new BigDecimal("2"),"Family event"),"employee@example.com");assertThat(request.status()).isEqualTo("PENDING");assertThat(service.decide(request.id(),new DecideLeaveRequest("APPROVED","Approved"),"hr@example.com").status()).isEqualTo("APPROVED");assertThat(service.balances(employeeA,2026).getFirst().available()).isEqualByComparingTo("8");}
 @Test void typesAndRequestsAreTenantIsolated(){service.request(new CreateLeaveRequest(employeeA,typeA,LocalDate.of(2026,10,1),LocalDate.of(2026,10,1),BigDecimal.ONE,"Personal"),"user");TenantContext.set(tenantB);assertThat(service.types()).isEmpty();assertThat(service.requests(null,null)).isEmpty();assertThatThrownBy(()->service.request(new CreateLeaveRequest(employeeA,typeA,LocalDate.of(2026,10,2),LocalDate.of(2026,10,2),BigDecimal.ONE,"Invalid"),"user")).isInstanceOfSatisfying(ResponseStatusException.class,e->assertThat(e.getStatusCode()).isIn(HttpStatus.NOT_FOUND,HttpStatus.CONFLICT));}
 @Test void rejectsOverlapAndInsufficientBalance(){service.request(new CreateLeaveRequest(employeeA,typeA,LocalDate.of(2026,11,1),LocalDate.of(2026,11,3),new BigDecimal("3"),"First"),"user");assertThatThrownBy(()->service.request(new CreateLeaveRequest(employeeA,typeA,LocalDate.of(2026,11,3),LocalDate.of(2026,11,4),BigDecimal.ONE,"Overlap"),"user")).isInstanceOf(ResponseStatusException.class);assertThatThrownBy(()->service.request(new CreateLeaveRequest(employeeA,typeA,LocalDate.of(2026,12,1),LocalDate.of(2026,12,9),new BigDecimal("8"),"Too much"),"user")).isInstanceOf(ResponseStatusException.class);}
 private SaveLeaveTypeRequest type(String code){return new SaveLeaveTypeRequest(code,"Casual Leave",true,new BigDecimal("12"),"ANNUAL",new BigDecimal("0.5"),new BigDecimal("5"),true,new BigDecimal("3"),false,false,"ACTIVE");}
 private void schema(){db.sql("CREATE TABLE tenant(id UUID PRIMARY KEY)").update();db.sql("CREATE TABLE employment(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,UNIQUE(id,tenant_id))").update();db.sql("CREATE TABLE leave_type(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,code VARCHAR(40),name VARCHAR(160),paid BOOLEAN,annual_entitlement NUMERIC(7,2),accrual_frequency VARCHAR(20),minimum_days NUMERIC(7,2),maximum_days NUMERIC(7,2),half_day_allowed BOOLEAN,carry_forward_limit NUMERIC(7,2),negative_balance_allowed BOOLEAN,supporting_document_required BOOLEAN,status VARCHAR(20),updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(tenant_id,code),UNIQUE(id,tenant_id))").update();db.sql("CREATE TABLE leave_balance(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,employment_id UUID,leave_type_id UUID,leave_year INT,opening_balance NUMERIC(7,2),accrued NUMERIC(7,2),adjusted NUMERIC(7,2),used NUMERIC(7,2),updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(tenant_id,employment_id,leave_type_id,leave_year),FOREIGN KEY(employment_id,tenant_id) REFERENCES employment(id,tenant_id),FOREIGN KEY(leave_type_id,tenant_id) REFERENCES leave_type(id,tenant_id))").update();db.sql("CREATE TABLE leave_request(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,employment_id UUID,leave_type_id UUID,start_date DATE,end_date DATE,requested_days NUMERIC(7,2),reason VARCHAR(1000),status VARCHAR(30) DEFAULT 'PENDING',requested_by VARCHAR(255),requested_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,decided_by VARCHAR(255),decided_at TIMESTAMP WITH TIME ZONE,decision_comment VARCHAR(1000),updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(employment_id,tenant_id) REFERENCES employment(id,tenant_id),FOREIGN KEY(leave_type_id,tenant_id) REFERENCES leave_type(id,tenant_id))").update();}
}
