package com.multitenanterp.payroll;
import java.math.*;import java.util.*;

final class FormulaEvaluator {
 private final String expression;private final Map<String,BigDecimal> values;private int position;
 private FormulaEvaluator(String expression,Map<String,BigDecimal> values){this.expression=expression;this.values=values;}
 static BigDecimal evaluate(String expression,Map<String,BigDecimal> values){if(expression==null||expression.isBlank())throw new IllegalArgumentException("Formula is required");FormulaEvaluator p=new FormulaEvaluator(expression,values);BigDecimal value=p.sum();p.space();if(p.position!=expression.length())throw new IllegalArgumentException("Unexpected formula token at position "+p.position);return value;}
 static Set<String> references(String expression){if(expression==null)return Set.of();Set<String> result=new LinkedHashSet<>();for(int i=0;i<expression.length();){char c=expression.charAt(i);if(Character.isLetter(c)||c=='_'){int start=i++;while(i<expression.length()&&(Character.isLetterOrDigit(expression.charAt(i))||expression.charAt(i)=='_'))i++;result.add(expression.substring(start,i).toUpperCase(Locale.ROOT));}else i++;}return result;}
 private BigDecimal sum(){BigDecimal v=term();while(true){space();if(take('+'))v=v.add(term());else if(take('-'))v=v.subtract(term());else return v;}}
 private BigDecimal term(){BigDecimal v=factor();while(true){space();if(take('*'))v=v.multiply(factor());else if(take('/')){BigDecimal d=factor();if(d.signum()==0)throw new IllegalArgumentException("Division by zero");v=v.divide(d,12,RoundingMode.HALF_UP);}else return v;}}
 private BigDecimal factor(){space();if(take('-'))return factor().negate();if(take('(')){BigDecimal v=sum();space();if(!take(')'))throw new IllegalArgumentException("Missing closing parenthesis");return v;}if(position<expression.length()&&(Character.isLetter(expression.charAt(position))||expression.charAt(position)=='_')){int start=position++;while(position<expression.length()&&(Character.isLetterOrDigit(expression.charAt(position))||expression.charAt(position)=='_'))position++;String name=expression.substring(start,position).toUpperCase(Locale.ROOT);BigDecimal v=values.get(name);if(v==null)throw new IllegalArgumentException("Unknown component "+name);return v;}int start=position;while(position<expression.length()&&(Character.isDigit(expression.charAt(position))||expression.charAt(position)=='.'))position++;if(start==position)throw new IllegalArgumentException("Expected number, component, or parenthesis at position "+position);try{return new BigDecimal(expression.substring(start,position));}catch(NumberFormatException e){throw new IllegalArgumentException("Invalid number in formula");}}
 private void space(){while(position<expression.length()&&Character.isWhitespace(expression.charAt(position)))position++;}private boolean take(char c){if(position<expression.length()&&expression.charAt(position)==c){position++;return true;}return false;}
}
