package com.multitenanterp.payroll;
import com.multitenanterp.platform.tenant.TenantContext;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.http.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Service;import org.springframework.web.server.ResponseStatusException;import java.sql.Date;import java.sql.ResultSet;import java.sql.SQLException;import java.time.LocalDate;import java.util.*;
@Service
public class PayrollInputService{
 private final JdbcClient db;public PayrollInputService(JdbcClient db){this.db=db;}
 public List<StatutoryRule> rules(){return db.sql("SELECT * FROM statutory_rule WHERE tenant_id=:tenant ORDER BY code,effective_from DESC").param("tenant",tenant()).query(PayrollInputService::rule).list();}
 public StatutoryRule saveRule(UUID id,SaveStatutoryRuleRequest r){if(r.effectiveTo()!=null&&r.effectiveTo().isBefore(r.effectiveFrom()))throw bad("Effective-to date cannot precede effective-from date");String basis=norm(r.basisType());List<String> codes=r.baseComponentCodes()==null?List.of():r.baseComponentCodes().stream().filter(Objects::nonNull).map(PayrollInputService::norm).distinct().toList();if(basis.equals("COMPONENTS")&&codes.isEmpty())throw bad("Component-based rules require at least one base component code");boolean create=id==null;id=create?UUID.randomUUID():id;try{int count=(create?db.sql("INSERT INTO statutory_rule(id,tenant_id,code,name,result_type,basis_type,base_component_codes,rate_percent,eligibility_ceiling,contribution_ceiling,rounding_scale,effective_from,effective_to,status) VALUES(:id,:tenant,:code,:name,:result,:basis,:codes,:rate,:eligibility,:contribution,:scale,:from,:to,:status)"):db.sql("UPDATE statutory_rule SET code=:code,name=:name,result_type=:result,basis_type=:basis,base_component_codes=:codes,rate_percent=:rate,eligibility_ceiling=:eligibility,contribution_ceiling=:contribution,rounding_scale=:scale,effective_from=:from,effective_to=:to,status=:status,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND tenant_id=:tenant")).param("id",id).param("tenant",tenant()).param("code",norm(r.code())).param("name",r.name().trim()).param("result",norm(r.resultType())).param("basis",basis).param("codes",String.join(",",codes)).param("rate",r.ratePercent()).param("eligibility",r.eligibilityCeiling()).param("contribution",r.contributionCeiling()).param("scale",r.roundingScale()).param("from",r.effectiveFrom()).param("to",r.effectiveTo()).param("status",r.status()==null?"DRAFT":norm(r.status())).update();if(count==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Statutory rule not found");}catch(DataIntegrityViolationException e){throw new ResponseStatusException(HttpStatus.CONFLICT,"Statutory rule values, dates, or code conflict");}UUID saved=id;return rules().stream().filter(x->x.id().equals(saved)).findFirst().orElseThrow();}
 public List<PayrollVariableInput> variables(int year,int month){return db.sql("SELECT * FROM payroll_variable_input WHERE tenant_id=:tenant AND payroll_year=:year AND payroll_month=:month ORDER BY employment_id,code").param("tenant",tenant()).param("year",year).param("month",month).query(PayrollInputService::variable).list();}
 public PayrollVariableInput saveVariable(UUID id,SavePayrollVariableInputRequest r,String actor){boolean create=id==null;id=create?UUID.randomUUID():id;try{int count=(create?db.sql("INSERT INTO payroll_variable_input(id,tenant_id,employment_id,payroll_year,payroll_month,code,name,input_type,amount,notes,created_by) VALUES(:id,:tenant,:employee,:year,:month,:code,:name,:type,:amount,:notes,:actor)"):db.sql("UPDATE payroll_variable_input SET employment_id=:employee,payroll_year=:year,payroll_month=:month,code=:code,name=:name,input_type=:type,amount=:amount,notes=:notes,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND tenant_id=:tenant")).param("id",id).param("tenant",tenant()).param("employee",r.employmentId()).param("year",r.year()).param("month",r.month()).param("code",norm(r.code())).param("name",r.name().trim()).param("type",norm(r.inputType())).param("amount",r.amount()).param("notes",blank(r.notes())).param("actor",actor).update();if(count==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Variable input not found");}catch(DataIntegrityViolationException e){throw new ResponseStatusException(HttpStatus.CONFLICT,"Variable input conflicts or references another company");}UUID saved=id;return variables(r.year(),r.month()).stream().filter(x->x.id().equals(saved)).findFirst().orElseThrow();}
 static StatutoryRule rule(ResultSet r,int n)throws SQLException{return new StatutoryRule(r.getObject("id",UUID.class),r.getString("code"),r.getString("name"),r.getString("result_type"),r.getString("basis_type"),split(r.getString("base_component_codes")),r.getBigDecimal("rate_percent"),r.getBigDecimal("eligibility_ceiling"),r.getBigDecimal("contribution_ceiling"),r.getInt("rounding_scale"),date(r,"effective_from"),date(r,"effective_to"),r.getString("status"));}
 static PayrollVariableInput variable(ResultSet r,int n)throws SQLException{return new PayrollVariableInput(r.getObject("id",UUID.class),r.getObject("employment_id",UUID.class),r.getInt("payroll_year"),r.getInt("payroll_month"),r.getString("code"),r.getString("name"),r.getString("input_type"),r.getBigDecimal("amount"),r.getString("notes"),r.getString("created_by"),r.getTimestamp("created_at").toInstant());}
 private static List<String> split(String s){return s==null||s.isBlank()?List.of():Arrays.asList(s.split(","));}private static LocalDate date(ResultSet r,String c)throws SQLException{Date d=r.getDate(c);return d==null?null:d.toLocalDate();}private static UUID tenant(){return TenantContext.requireTenantId();}private static String norm(String s){return s.trim().toUpperCase(Locale.ROOT);}private static String blank(String s){return s==null||s.isBlank()?null:s.trim();}private static ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}
}
