package com.multitenanterp.payroll;

import com.multitenanterp.platform.tenant.TenantContext;
import org.springframework.http.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;
import java.math.*;import java.sql.*;import java.time.*;import java.util.*;

@Service
public class PayrollCalculationService {
 private final JdbcClient db;public PayrollCalculationService(JdbcClient db){this.db=db;}

 @Transactional public PayrollRun calculate(int year,int month,String actor){UUID tenant=TenantContext.requireTenantId();YearMonth period;try{period=YearMonth.of(year,month);}catch(DateTimeException e){throw bad("Invalid payroll period");}LocalDate asOf=period.atEndOfMonth();
  if(db.sql("SELECT COUNT(*) FROM payroll_run WHERE tenant_id=:tenant AND payroll_year=:year AND payroll_month=:month AND status NOT IN ('DRAFT','CALCULATED')").param("tenant",tenant).param("year",year).param("month",month).query(Integer.class).single()>0)throw conflict("Payroll is already under review or locked for this period");
  UUID runId=db.sql("SELECT id FROM payroll_run WHERE tenant_id=:tenant AND payroll_year=:year AND payroll_month=:month").param("tenant",tenant).param("year",year).param("month",month).query(UUID.class).optional().orElse(UUID.randomUUID());
  db.sql("DELETE FROM payroll_component_result WHERE tenant_id=:tenant AND payroll_employee_result_id IN (SELECT id FROM payroll_employee_result WHERE tenant_id=:tenant AND payroll_run_id=:run)").param("tenant",tenant).param("run",runId).update();db.sql("DELETE FROM payroll_employee_result WHERE tenant_id=:tenant AND payroll_run_id=:run").param("tenant",tenant).param("run",runId).update();
  db.sql("INSERT INTO payroll_run(id,tenant_id,payroll_year,payroll_month,status,calculated_at,calculated_by) VALUES(:id,:tenant,:year,:month,'CALCULATED',CURRENT_TIMESTAMP,:actor) ON CONFLICT(tenant_id,payroll_year,payroll_month) DO UPDATE SET status='CALCULATED',calculated_at=CURRENT_TIMESTAMP,calculated_by=EXCLUDED.calculated_by").param("id",runId).param("tenant",tenant).param("year",year).param("month",month).param("actor",actor).update();
  String basis=db.sql("SELECT working_day_basis FROM payroll_setting WHERE tenant_id=:tenant").param("tenant",tenant).query(String.class).optional().orElse("CALENDAR_DAYS");
  List<Assignment> assignments=db.sql("SELECT a.id,a.employment_id,a.salary_structure_id,a.annual_ctc,e.joining_date,e.exit_date FROM employee_salary_assignment a JOIN employment e ON e.id=a.employment_id AND e.tenant_id=a.tenant_id WHERE a.tenant_id=:tenant AND a.effective_from<=:date AND (a.effective_to IS NULL OR a.effective_to>=:date) AND e.joining_date<=:date AND (e.exit_date IS NULL OR e.exit_date>=:start) AND NOT EXISTS (SELECT 1 FROM employee_salary_assignment newer WHERE newer.tenant_id=a.tenant_id AND newer.employment_id=a.employment_id AND newer.effective_from<=:date AND (newer.effective_to IS NULL OR newer.effective_to>=:date) AND newer.effective_from>a.effective_from)").param("tenant",tenant).param("date",asOf).param("start",period.atDay(1)).query((r,n)->new Assignment(r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getObject(3,UUID.class),r.getBigDecimal(4),r.getDate(5).toLocalDate(),r.getDate(6)==null?null:r.getDate(6).toLocalDate())).list();
  for(Assignment assignment:assignments)calculateEmployee(tenant,runId,period,basis,assignment);
  return run(runId);
 }
 public PayrollRun get(int year,int month){UUID id=db.sql("SELECT id FROM payroll_run WHERE tenant_id=:tenant AND payroll_year=:year AND payroll_month=:month").param("tenant",TenantContext.requireTenantId()).param("year",year).param("month",month).query(UUID.class).optional().orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Payroll run not found"));return run(id);}
 private void calculateEmployee(UUID tenant,UUID runId,YearMonth period,String basis,Assignment assignment){LocalDate asOf=period.atEndOfMonth();BigDecimal unpaid=unpaidLeaveDays(tenant,assignment.employmentId,period);BigDecimal absent=db.sql("SELECT COALESCE(SUM(CASE WHEN status='ABSENT' THEN 1 WHEN status='HALF_DAY' THEN 0.5 ELSE 0 END),0) FROM attendance_record WHERE tenant_id=:tenant AND employment_id=:employee AND attendance_date BETWEEN :start AND :end").param("tenant",tenant).param("employee",assignment.employmentId).param("start",period.atDay(1)).param("end",asOf).query(BigDecimal.class).single();int overtime=db.sql("SELECT COALESCE(SUM(overtime_minutes),0) FROM attendance_record WHERE tenant_id=:tenant AND employment_id=:employee AND attendance_date BETWEEN :start AND :end").param("tenant",tenant).param("employee",assignment.employmentId).param("start",period.atDay(1)).param("end",asOf).query(Integer.class).single();PayrollProration proration=PayrollProrationCalculator.calculate(period,basis,assignment.joiningDate,assignment.exitDate,unpaid,absent,overtime);List<Line> lines=db.sql("SELECT l.salary_component_id,l.sequence_number,l.component_value,l.formula_expression,c.code,c.name,c.component_type,c.calculation_type,c.calculation_base_code,c.default_value,c.included_in_gross,c.included_in_ctc,c.included_in_net,c.rounding_scale,c.prorated FROM salary_structure_component l JOIN salary_component c ON c.id=l.salary_component_id AND c.tenant_id=l.tenant_id WHERE l.tenant_id=:tenant AND l.salary_structure_id=:structure AND c.status='ACTIVE' AND c.effective_from<=:date AND (c.effective_to IS NULL OR c.effective_to>=:date) ORDER BY l.sequence_number").param("tenant",tenant).param("structure",assignment.structureId).param("date",asOf).query(PayrollCalculationService::line).list();if(lines.isEmpty())throw bad("Salary structure has no active components for employee "+assignment.employmentId);
  Map<String,Line> byCode=new LinkedHashMap<>();for(Line line:lines){String code=line.code.toUpperCase(Locale.ROOT);if(byCode.put(code,line)!=null)throw bad("Duplicate active salary component code "+code);}
  Map<String,BigDecimal> values=new LinkedHashMap<>();values.put("ANNUAL_CTC",assignment.annualCtc);values.put("MONTHLY_CTC",assignment.annualCtc.divide(BigDecimal.valueOf(12),12,RoundingMode.HALF_UP));values.put("PERIOD_DAYS",proration.periodDays());values.put("PAYABLE_DAYS",proration.payableDays());values.put("UNPAID_LEAVE_DAYS",proration.unpaidLeaveDays());values.put("ABSENT_DAYS",proration.absentDays());values.put("OVERTIME_HOURS",BigDecimal.valueOf(proration.overtimeMinutes()).divide(BigDecimal.valueOf(60),4,RoundingMode.HALF_UP));Set<String> pending=new LinkedHashSet<>(byCode.keySet());
  try{while(!pending.isEmpty()){boolean progressed=false;for(String code:new ArrayList<>(pending)){Line line=byCode.get(code);Set<String> refs=dependencies(line);Set<String> unknown=new LinkedHashSet<>(refs);unknown.removeAll(byCode.keySet());unknown.removeAll(SPECIAL_VARIABLES);if(!unknown.isEmpty())throw new IllegalArgumentException("Component "+code+" references unknown component "+unknown.iterator().next());if(!values.keySet().containsAll(refs))continue;BigDecimal amount=switch(line.calculationType){case "FIXED"->line.value!=null?line.value:line.defaultValue;case "PERCENTAGE"->values.get(line.baseCode.toUpperCase(Locale.ROOT)).multiply(line.value!=null?line.value:line.defaultValue).divide(BigDecimal.valueOf(100),12,RoundingMode.HALF_UP);case "FORMULA"->FormulaEvaluator.evaluate(line.formula,values);default->throw new IllegalArgumentException("Unsupported calculation type "+line.calculationType);};values.put(code,amount.setScale(line.roundingScale,RoundingMode.HALF_UP));pending.remove(code);progressed=true;}if(!progressed)throw new IllegalArgumentException("Circular salary component dependency: "+String.join(", ",pending));}for(Line line:lines)if(line.prorated){String code=line.code.toUpperCase(Locale.ROOT);values.put(code,values.get(code).multiply(proration.factor()).setScale(line.roundingScale,RoundingMode.HALF_UP));}}catch(IllegalArgumentException e){throw bad(e.getMessage());}
  BigDecimal gross=BigDecimal.ZERO,deductions=BigDecimal.ZERO,employer=BigDecimal.ZERO,ctc=BigDecimal.ZERO,net=BigDecimal.ZERO;for(Line l:lines){BigDecimal amount=values.get(l.code.toUpperCase(Locale.ROOT));if(l.gross)gross=gross.add(amount);if(l.ctc)ctc=ctc.add(amount);if(l.net)net=l.type.equals("DEDUCTION")?net.subtract(amount):l.type.equals("EARNING")?net.add(amount):net;if(l.type.equals("DEDUCTION"))deductions=deductions.add(amount);if(l.type.equals("EMPLOYER_CONTRIBUTION"))employer=employer.add(amount);}
  int scale=2;UUID result=UUID.randomUUID();db.sql("INSERT INTO payroll_employee_result(id,tenant_id,payroll_run_id,employment_id,salary_assignment_id,gross_pay,deductions,employer_contributions,net_pay,ctc,period_days,eligible_days,unpaid_leave_days,absent_days,payable_days,proration_factor,overtime_minutes) VALUES(:id,:tenant,:run,:employee,:assignment,:gross,:deductions,:employer,:net,:ctc,:period,:eligible,:unpaid,:absent,:payable,:factor,:overtime)").param("id",result).param("tenant",tenant).param("run",runId).param("employee",assignment.employmentId).param("assignment",assignment.id).param("gross",gross.setScale(scale,RoundingMode.HALF_UP)).param("deductions",deductions.setScale(scale,RoundingMode.HALF_UP)).param("employer",employer.setScale(scale,RoundingMode.HALF_UP)).param("net",net.setScale(scale,RoundingMode.HALF_UP)).param("ctc",ctc.setScale(scale,RoundingMode.HALF_UP)).param("period",proration.periodDays()).param("eligible",proration.eligibleDays()).param("unpaid",proration.unpaidLeaveDays()).param("absent",proration.absentDays()).param("payable",proration.payableDays()).param("factor",proration.factor()).param("overtime",proration.overtimeMinutes()).update();for(Line l:lines)db.sql("INSERT INTO payroll_component_result(id,tenant_id,payroll_employee_result_id,salary_component_id,component_code,component_name,component_type,amount,sequence_number) VALUES(:id,:tenant,:result,:component,:code,:name,:type,:amount,:sequence)").param("id",UUID.randomUUID()).param("tenant",tenant).param("result",result).param("component",l.componentId).param("code",l.code).param("name",l.name).param("type",l.type).param("amount",values.get(l.code.toUpperCase(Locale.ROOT))).param("sequence",l.sequence).update();
 }
 private PayrollRun run(UUID id){UUID tenant=TenantContext.requireTenantId();Run base=db.sql("SELECT * FROM payroll_run WHERE id=:id AND tenant_id=:tenant").param("id",id).param("tenant",tenant).query((r,n)->new Run(r.getObject("id",UUID.class),r.getInt("payroll_year"),r.getInt("payroll_month"),r.getString("status"),r.getTimestamp("calculated_at").toInstant(),r.getString("calculated_by"))).single();List<PayrollEmployeeResult> employees=db.sql("SELECT * FROM payroll_employee_result WHERE tenant_id=:tenant AND payroll_run_id=:run ORDER BY employment_id").param("tenant",tenant).param("run",id).query((r,n)->new PayrollEmployeeResult(r.getObject("id",UUID.class),r.getObject("employment_id",UUID.class),r.getObject("salary_assignment_id",UUID.class),r.getBigDecimal("gross_pay"),r.getBigDecimal("deductions"),r.getBigDecimal("employer_contributions"),r.getBigDecimal("net_pay"),r.getBigDecimal("ctc"),new PayrollProration(r.getBigDecimal("period_days"),r.getBigDecimal("eligible_days"),r.getBigDecimal("unpaid_leave_days"),r.getBigDecimal("absent_days"),r.getBigDecimal("payable_days"),r.getBigDecimal("proration_factor"),r.getInt("overtime_minutes")),components(r.getObject("id",UUID.class)))).list();return new PayrollRun(base.id,base.year,base.month,base.status,base.at,base.by,employees);}
 private List<PayrollComponentResult> components(UUID result){return db.sql("SELECT * FROM payroll_component_result WHERE tenant_id=:tenant AND payroll_employee_result_id=:result ORDER BY sequence_number").param("tenant",TenantContext.requireTenantId()).param("result",result).query((r,n)->new PayrollComponentResult(r.getObject("id",UUID.class),r.getObject("salary_component_id",UUID.class),r.getString("component_code"),r.getString("component_name"),r.getString("component_type"),r.getBigDecimal("amount"),r.getInt("sequence_number"))).list();}
 private static Set<String> dependencies(Line l){if(l.calculationType.equals("PERCENTAGE"))return Set.of(l.baseCode.toUpperCase(Locale.ROOT));if(l.calculationType.equals("FORMULA"))return FormulaEvaluator.references(l.formula);return Set.of();}
 private BigDecimal unpaidLeaveDays(UUID tenant,UUID employee,YearMonth period){return db.sql("SELECT COALESCE(SUM(lr.requested_days * ((LEAST(lr.end_date,:end)-GREATEST(lr.start_date,:start)+1) * 1.0 / (lr.end_date-lr.start_date+1))),0) FROM leave_request lr JOIN leave_type lt ON lt.id=lr.leave_type_id AND lt.tenant_id=lr.tenant_id WHERE lr.tenant_id=:tenant AND lr.employment_id=:employee AND lr.status='APPROVED' AND lt.paid=FALSE AND lr.start_date<=:end AND lr.end_date>=:start").param("tenant",tenant).param("employee",employee).param("start",period.atDay(1)).param("end",period.atEndOfMonth()).query(BigDecimal.class).single();}
 private static Line line(ResultSet r,int n)throws SQLException{return new Line(r.getObject(1,UUID.class),r.getInt(2),r.getBigDecimal(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getString(9),r.getBigDecimal(10),r.getBoolean(11),r.getBoolean(12),r.getBoolean(13),r.getInt(14),r.getBoolean(15));}
 private static final Set<String> SPECIAL_VARIABLES=Set.of("ANNUAL_CTC","MONTHLY_CTC","PERIOD_DAYS","PAYABLE_DAYS","UNPAID_LEAVE_DAYS","ABSENT_DAYS","OVERTIME_HOURS");
 private record Assignment(UUID id,UUID employmentId,UUID structureId,BigDecimal annualCtc,LocalDate joiningDate,LocalDate exitDate){}private record Line(UUID componentId,int sequence,BigDecimal value,String formula,String code,String name,String type,String calculationType,String baseCode,BigDecimal defaultValue,boolean gross,boolean ctc,boolean net,int roundingScale,boolean prorated){}private record Run(UUID id,int year,int month,String status,Instant at,String by){}
 private static ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}private static ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}
}
