package com.multitenanterp.payroll;
import com.multitenanterp.employee.DocumentStorage;import com.multitenanterp.platform.tenant.TenantContext;import org.springframework.http.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import java.io.*;import java.math.BigDecimal;import java.security.*;import java.sql.*;import java.time.Instant;import java.util.*;
@Service
public class PayslipService{
 private final JdbcClient db;private final DocumentStorage storage;private final PayslipPdfGenerator pdf;
 public List<Payslip> releasedForEmployee(UUID employee){
  return db.sql(BASE+" WHERE p.tenant_id=:tenant AND p.employment_id=:employee AND p.status='RELEASED' AND pr.status IN ('LOCKED','PAID') ORDER BY pr.payroll_year DESC,pr.payroll_month DESC")
   .param("tenant",tenant()).param("employee",employee).query(PayslipService::map).list();
 }
 public PayslipDownload downloadReleased(UUID id,UUID employee){
  Stored stored=db.sql(BASE.replace(" FROM payslip",",p.storage_key FROM payslip")+" WHERE p.id=:id AND p.tenant_id=:tenant AND p.employment_id=:employee AND p.status='RELEASED' AND pr.status IN ('LOCKED','PAID')")
   .param("id",id).param("tenant",tenant()).param("employee",employee)
   .query((r,n)->new Stored(map(r,n),r.getString("storage_key"))).optional().orElseThrow(()->missing("Payslip"));
  var resource=storage.load(stored.key());if(!resource.exists())throw missing("Payslip content");
  return new PayslipDownload(stored.metadata(),resource);
 }
 public PayslipService(JdbcClient db,DocumentStorage storage,PayslipPdfGenerator pdf){this.db=db;this.storage=storage;this.pdf=pdf;}
 public List<Payslip> list(int year,int month){UUID run=runId(year,month);return db.sql(BASE+" WHERE p.tenant_id=:tenant AND p.payroll_run_id=:run ORDER BY e.employee_number").param("tenant",tenant()).param("run",run).query(PayslipService::map).list();}
 @Transactional public List<Payslip> generate(int year,int month,String actor){UUID tenant=tenant(),run=runId(year,month);String status=db.sql("SELECT status FROM payroll_run WHERE id=:run AND tenant_id=:tenant").param("run",run).param("tenant",tenant).query(String.class).single();if(!status.equals("LOCKED")&&!status.equals("PAID"))throw conflict("Payslips can only be generated for locked or paid payroll");List<Source> sources=db.sql("SELECT r.id,r.employment_id,r.gross_pay,r.deductions,r.net_pay,r.period_days,r.payable_days,e.employee_number,TRIM(CONCAT(p.first_name,' ',COALESCE(p.middle_name||' ',''),p.last_name)),t.legal_name,COALESCE(cp.registered_address,'') FROM payroll_employee_result r JOIN employment e ON e.id=r.employment_id AND e.tenant_id=r.tenant_id JOIN person p ON p.id=e.person_id AND p.tenant_id=e.tenant_id JOIN tenant t ON t.id=r.tenant_id LEFT JOIN company_profile cp ON cp.tenant_id=t.id WHERE r.tenant_id=:tenant AND r.payroll_run_id=:run AND NOT EXISTS(SELECT 1 FROM payslip ps WHERE ps.tenant_id=r.tenant_id AND ps.payroll_run_id=r.payroll_run_id AND ps.employment_id=r.employment_id) ORDER BY e.employee_number").param("tenant",tenant).param("run",run).query((r,n)->new Source(r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getBigDecimal(3),r.getBigDecimal(4),r.getBigDecimal(5),r.getBigDecimal(6),r.getBigDecimal(7),r.getString(8),r.getString(9),r.getString(10),r.getString(11))).list();for(Source source:sources)generateOne(tenant,run,year,month,source,actor);return list(year,month);}
 @Transactional public List<Payslip> release(int year,int month,String actor){UUID tenant=tenant(),run=runId(year,month);String status=db.sql("SELECT status FROM payroll_run WHERE id=:run AND tenant_id=:tenant").param("run",run).param("tenant",tenant).query(String.class).single();if(!status.equals("LOCKED")&&!status.equals("PAID"))throw conflict("Payslips can only be released for locked or paid payroll");int available=db.sql("SELECT COUNT(*) FROM payslip WHERE tenant_id=:tenant AND payroll_run_id=:run").param("tenant",tenant).param("run",run).query(Integer.class).single();if(available==0)throw conflict("Generate payslips before release");db.sql("UPDATE payslip SET status='RELEASED',released_by=:actor,released_at=CURRENT_TIMESTAMP WHERE tenant_id=:tenant AND payroll_run_id=:run AND status='GENERATED'").param("actor",actor).param("tenant",tenant).param("run",run).update();return list(year,month);}
 public PayslipDownload download(int year,int month,UUID id){UUID run=runId(year,month);Stored stored=db.sql(BASE.replace(" FROM payslip",",p.storage_key FROM payslip")+" WHERE p.id=:id AND p.tenant_id=:tenant AND p.payroll_run_id=:run").param("id",id).param("tenant",tenant()).param("run",run).query((r,n)->new Stored(map(r,n),r.getString("storage_key"))).optional().orElseThrow(()->missing("Payslip"));var resource=storage.load(stored.key());if(!resource.exists())throw missing("Payslip content");return new PayslipDownload(stored.metadata(),resource);}
 private void generateOne(UUID tenant,UUID run,int year,int month,Source s,String actor){UUID id=UUID.randomUUID();List<PayslipPdfGenerator.Item> items=db.sql("SELECT component_name,component_type,amount FROM payroll_component_result WHERE tenant_id=:tenant AND payroll_employee_result_id=:result AND component_type IN ('EARNING','DEDUCTION') UNION ALL SELECT name,result_type,amount FROM payroll_adjustment_result WHERE tenant_id=:tenant AND payroll_employee_result_id=:result AND result_type IN ('EARNING','DEDUCTION') ORDER BY 2,1").param("tenant",tenant).param("result",s.resultId).query((r,n)->new PayslipPdfGenerator.Item(r.getString(1),r.getString(2),r.getBigDecimal(3))).list();byte[] content=pdf.generate(new PayslipPdfGenerator.PayslipData(id,s.company,s.address,s.number,s.name,year,month,s.periodDays,s.payableDays,s.gross,s.deductions,s.net,items));String key=tenant+"/"+s.employmentId+"/"+id,fileName="payslip-"+year+"-"+String.format("%02d",month)+"-"+s.number.replaceAll("[^A-Za-z0-9_-]","_")+".pdf";try{storage.store(key,new ByteArrayInputStream(content));db.sql("INSERT INTO payslip(id,tenant_id,payroll_run_id,payroll_employee_result_id,employment_id,file_name,storage_key,size_bytes,sha256,status,generated_by) VALUES(:id,:tenant,:run,:result,:employment,:name,:key,:size,:sha,'GENERATED',:actor)").param("id",id).param("tenant",tenant).param("run",run).param("result",s.resultId).param("employment",s.employmentId).param("name",fileName).param("key",key).param("size",content.length).param("sha",sha256(content)).param("actor",actor).update();}catch(Exception e){try{storage.delete(key);}catch(IOException ignored){}throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,"Unable to store payslip",e);}}
 private UUID runId(int year,int month){return db.sql("SELECT id FROM payroll_run WHERE tenant_id=:tenant AND payroll_year=:year AND payroll_month=:month").param("tenant",tenant()).param("year",year).param("month",month).query(UUID.class).optional().orElseThrow(()->missing("Payroll run"));}private static String sha256(byte[] value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}private static Instant instant(ResultSet r,String name)throws SQLException{java.sql.Timestamp t=r.getTimestamp(name);return t==null?null:t.toInstant();}
 private static Payslip map(ResultSet r,int n)throws SQLException{return new Payslip(r.getObject("id",UUID.class),r.getObject("payroll_run_id",UUID.class),r.getObject("payroll_employee_result_id",UUID.class),r.getObject("employment_id",UUID.class),r.getString("employee_number"),r.getString("employee_name"),r.getInt("payroll_year"),r.getInt("payroll_month"),r.getString("file_name"),r.getLong("size_bytes"),r.getString("sha256"),r.getString("status"),r.getString("generated_by"),instant(r,"generated_at"),r.getString("released_by"),instant(r,"released_at"));}private static UUID tenant(){return TenantContext.requireTenantId();}private static ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}private static ResponseStatusException missing(String n){return new ResponseStatusException(HttpStatus.NOT_FOUND,n+" not found");}
 private static final String BASE="SELECT p.id,p.payroll_run_id,p.payroll_employee_result_id,p.employment_id,e.employee_number,TRIM(CONCAT(pe.first_name,' ',COALESCE(pe.middle_name||' ',''),pe.last_name)) employee_name,pr.payroll_year,pr.payroll_month,p.file_name,p.size_bytes,p.sha256,p.status,p.generated_by,p.generated_at,p.released_by,p.released_at FROM payslip p JOIN payroll_run pr ON pr.id=p.payroll_run_id AND pr.tenant_id=p.tenant_id JOIN employment e ON e.id=p.employment_id AND e.tenant_id=p.tenant_id JOIN person pe ON pe.id=e.person_id AND pe.tenant_id=e.tenant_id";
 private record Source(UUID resultId,UUID employmentId,BigDecimal gross,BigDecimal deductions,BigDecimal net,BigDecimal periodDays,BigDecimal payableDays,String number,String name,String company,String address){}private record Stored(Payslip metadata,String key){}
}
