package com.multitenanterp.payroll;
import jakarta.validation.Valid;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/payroll/structure") @PreAuthorize("@tenantAuthorization.hasAnyRole('SYSTEM_ADMIN','GROUP_ADMIN','COMPANY_ADMIN','PAYROLL_MANAGER','PAYROLL_EXECUTIVE')")
public class SalaryStructureController{
 private final SalaryStructureService service;public SalaryStructureController(SalaryStructureService service){this.service=service;}
 @GetMapping("/settings") public PayrollSetting setting(){return service.setting();}@PutMapping("/settings") public PayrollSetting setting(@Valid @RequestBody SavePayrollSettingRequest r){return service.saveSetting(r);}
 @GetMapping("/components") public List<SalaryComponent> components(){return service.components();}@PostMapping("/components") @ResponseStatus(HttpStatus.CREATED) public SalaryComponent component(@Valid @RequestBody SaveSalaryComponentRequest r){return service.saveComponent(null,r);}@PutMapping("/components/{id}") public SalaryComponent component(@PathVariable UUID id,@Valid @RequestBody SaveSalaryComponentRequest r){return service.saveComponent(id,r);}
 @GetMapping("/templates") public List<SalaryStructure> structures(){return service.structures();}@PostMapping("/templates") @ResponseStatus(HttpStatus.CREATED) public SalaryStructure structure(@Valid @RequestBody SaveSalaryStructureRequest r){return service.saveStructure(null,r);}@PutMapping("/templates/{id}") public SalaryStructure structure(@PathVariable UUID id,@Valid @RequestBody SaveSalaryStructureRequest r){return service.saveStructure(id,r);}
 @GetMapping("/assignments") public List<EmployeeSalaryAssignment> assignments(@RequestParam UUID employmentId){return service.assignments(employmentId);}@PostMapping("/assignments") @ResponseStatus(HttpStatus.CREATED) public EmployeeSalaryAssignment assignment(@Valid @RequestBody SaveEmployeeSalaryAssignmentRequest r,Authentication a){return service.assign(r,a.getName());}
}
