package com.multitenanterp.payroll;

import com.multitenanterp.platform.tenant.TenantContext;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import java.sql.*;
import java.time.LocalDate;
import java.util.*;

@Service
public class SalaryStructureService {
 private final JdbcClient db;
 public SalaryStructureService(JdbcClient db){this.db=db;}

 public PayrollSetting setting(){return db.sql("SELECT * FROM payroll_setting WHERE tenant_id=:tenant").param("tenant",tenant()).query((r,n)->new PayrollSetting(r.getObject("tenant_id",UUID.class),r.getString("pay_frequency"),r.getInt("attendance_cutoff_day"),r.getInt("payment_day"),r.getString("working_day_basis"),r.getInt("rounding_scale"),r.getString("negative_salary_policy"))).optional().orElse(new PayrollSetting(tenant(),"MONTHLY",25,7,"CALENDAR_DAYS",2,"HOLD"));}
 public PayrollSetting saveSetting(SavePayrollSettingRequest r){db.sql("INSERT INTO payroll_setting(tenant_id,pay_frequency,attendance_cutoff_day,payment_day,working_day_basis,rounding_scale,negative_salary_policy) VALUES(:tenant,:frequency,:cutoff,:payment,:basis,:scale,:negative) ON CONFLICT (tenant_id) DO UPDATE SET pay_frequency=EXCLUDED.pay_frequency,attendance_cutoff_day=EXCLUDED.attendance_cutoff_day,payment_day=EXCLUDED.payment_day,working_day_basis=EXCLUDED.working_day_basis,rounding_scale=EXCLUDED.rounding_scale,negative_salary_policy=EXCLUDED.negative_salary_policy,updated_at=CURRENT_TIMESTAMP").param("tenant",tenant()).param("frequency",norm(r.payFrequency())).param("cutoff",r.attendanceCutoffDay()).param("payment",r.paymentDay()).param("basis",norm(r.workingDayBasis())).param("scale",r.roundingScale()).param("negative",norm(r.negativeSalaryPolicy())).update();return setting();}

 public List<SalaryComponent> components(){return db.sql("SELECT * FROM salary_component WHERE tenant_id=:tenant ORDER BY code,effective_from DESC").param("tenant",tenant()).query(SalaryStructureService::mapComponent).list();}
 public SalaryComponent saveComponent(UUID id,SaveSalaryComponentRequest r){dates(r.effectiveFrom(),r.effectiveTo());String calc=norm(r.calculationType());if((calc.equals("PERCENTAGE")||calc.equals("FORMULA"))&&blank(r.calculationBaseCode())==null)throw bad("Percentage and formula components require a calculation base code");boolean create=id==null;id=create?UUID.randomUUID():id;
  try{int count=(create?db.sql("INSERT INTO salary_component(id,tenant_id,code,name,component_type,calculation_type,calculation_base_code,default_value,taxable,pf_applicable,esi_applicable,prorated,included_in_gross,included_in_ctc,included_in_net,rounding_scale,effective_from,effective_to,status) VALUES(:id,:tenant,:code,:name,:type,:calc,:base,:value,:taxable,:pf,:esi,:prorated,:gross,:ctc,:net,:scale,:from,:to,:status)"):db.sql("UPDATE salary_component SET code=:code,name=:name,component_type=:type,calculation_type=:calc,calculation_base_code=:base,default_value=:value,taxable=:taxable,pf_applicable=:pf,esi_applicable=:esi,prorated=:prorated,included_in_gross=:gross,included_in_ctc=:ctc,included_in_net=:net,rounding_scale=:scale,effective_from=:from,effective_to=:to,status=:status,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND tenant_id=:tenant"))
   .param("id",id).param("tenant",tenant()).param("code",norm(r.code())).param("name",r.name().trim()).param("type",norm(r.componentType())).param("calc",calc).param("base",blank(r.calculationBaseCode())==null?null:norm(r.calculationBaseCode())).param("value",r.defaultValue()).param("taxable",r.taxable()).param("pf",r.pfApplicable()).param("esi",r.esiApplicable()).param("prorated",r.prorated()).param("gross",r.includedInGross()).param("ctc",r.includedInCtc()).param("net",r.includedInNet()).param("scale",r.roundingScale()).param("from",r.effectiveFrom()).param("to",r.effectiveTo()).param("status",r.status()==null?"ACTIVE":norm(r.status())).update();if(count==0)throw missing("Salary component");}catch(DataIntegrityViolationException e){throw conflict("Salary component code, type, or dates are invalid");}
  UUID saved=id;return components().stream().filter(x->x.id().equals(saved)).findFirst().orElseThrow();}

 public List<SalaryStructure> structures(){return db.sql("SELECT * FROM salary_structure WHERE tenant_id=:tenant ORDER BY name,effective_from DESC").param("tenant",tenant()).query((r,n)->new Base(r.getObject("id",UUID.class),r.getString("code"),r.getString("name"),r.getString("description"),date(r,"effective_from"),date(r,"effective_to"),r.getString("status"))).list().stream().map(b->new SalaryStructure(b.id,b.code,b.name,b.description,b.from,b.to,b.status,lines(b.id))).toList();}
 @Transactional public SalaryStructure saveStructure(UUID id,SaveSalaryStructureRequest r){dates(r.effectiveFrom(),r.effectiveTo());Set<UUID> ids=new HashSet<>();Set<Integer> sequences=new HashSet<>();for(var line:r.components())if(!ids.add(line.salaryComponentId())||!sequences.add(line.sequenceNumber()))throw bad("Components and sequence numbers must be unique");boolean create=id==null;id=create?UUID.randomUUID():id;
  try{int count=(create?db.sql("INSERT INTO salary_structure(id,tenant_id,code,name,description,effective_from,effective_to,status) VALUES(:id,:tenant,:code,:name,:description,:from,:to,:status)"):db.sql("UPDATE salary_structure SET code=:code,name=:name,description=:description,effective_from=:from,effective_to=:to,status=:status,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND tenant_id=:tenant")).param("id",id).param("tenant",tenant()).param("code",norm(r.code())).param("name",r.name().trim()).param("description",blank(r.description())).param("from",r.effectiveFrom()).param("to",r.effectiveTo()).param("status",r.status()==null?"DRAFT":norm(r.status())).update();if(count==0)throw missing("Salary structure");db.sql("DELETE FROM salary_structure_component WHERE tenant_id=:tenant AND salary_structure_id=:id").param("tenant",tenant()).param("id",id).update();for(var line:r.components())db.sql("INSERT INTO salary_structure_component(id,tenant_id,salary_structure_id,salary_component_id,sequence_number,component_value,formula_expression) VALUES(:line,:tenant,:structure,:component,:sequence,:value,:formula)").param("line",UUID.randomUUID()).param("tenant",tenant()).param("structure",id).param("component",line.salaryComponentId()).param("sequence",line.sequenceNumber()).param("value",line.value()).param("formula",blank(line.formulaExpression())).update();}catch(DataIntegrityViolationException e){throw conflict("Structure code, dates, or component company scope is invalid");}return structure(id);}

 public List<EmployeeSalaryAssignment> assignments(UUID employee){return db.sql("SELECT * FROM employee_salary_assignment WHERE tenant_id=:tenant AND employment_id=:employee ORDER BY effective_from DESC").param("tenant",tenant()).param("employee",employee).query(SalaryStructureService::mapAssignment).list();}
 public EmployeeSalaryAssignment assign(SaveEmployeeSalaryAssignmentRequest r,String actor){dates(r.effectiveFrom(),r.effectiveTo());UUID id=UUID.randomUUID();try{db.sql("INSERT INTO employee_salary_assignment(id,tenant_id,employment_id,salary_structure_id,effective_from,effective_to,annual_ctc,revision_reason,created_by) VALUES(:id,:tenant,:employee,:structure,:from,:to,:ctc,:reason,:actor)").param("id",id).param("tenant",tenant()).param("employee",r.employmentId()).param("structure",r.salaryStructureId()).param("from",r.effectiveFrom()).param("to",r.effectiveTo()).param("ctc",r.annualCtc()).param("reason",r.revisionReason().trim()).param("actor",actor).update();}catch(DataIntegrityViolationException e){throw conflict("Salary assignment conflicts with an existing revision or another company");}return assignments(r.employmentId()).stream().filter(x->x.id().equals(id)).findFirst().orElseThrow();}

 private SalaryStructure structure(UUID id){return structures().stream().filter(x->x.id().equals(id)).findFirst().orElseThrow(()->missing("Salary structure"));}
 private List<SalaryStructureLine> lines(UUID id){return db.sql("SELECT * FROM salary_structure_component WHERE tenant_id=:tenant AND salary_structure_id=:id ORDER BY sequence_number").param("tenant",tenant()).param("id",id).query((r,n)->new SalaryStructureLine(r.getObject("id",UUID.class),r.getObject("salary_component_id",UUID.class),r.getInt("sequence_number"),r.getBigDecimal("component_value"),r.getString("formula_expression"))).list();}
 private record Base(UUID id,String code,String name,String description,LocalDate from,LocalDate to,String status){}
 private static SalaryComponent mapComponent(ResultSet r,int n)throws SQLException{return new SalaryComponent(r.getObject("id",UUID.class),r.getString("code"),r.getString("name"),r.getString("component_type"),r.getString("calculation_type"),r.getString("calculation_base_code"),r.getBigDecimal("default_value"),r.getBoolean("taxable"),r.getBoolean("pf_applicable"),r.getBoolean("esi_applicable"),r.getBoolean("prorated"),r.getBoolean("included_in_gross"),r.getBoolean("included_in_ctc"),r.getBoolean("included_in_net"),r.getInt("rounding_scale"),date(r,"effective_from"),date(r,"effective_to"),r.getString("status"));}
 private static EmployeeSalaryAssignment mapAssignment(ResultSet r,int n)throws SQLException{return new EmployeeSalaryAssignment(r.getObject("id",UUID.class),r.getObject("employment_id",UUID.class),r.getObject("salary_structure_id",UUID.class),date(r,"effective_from"),date(r,"effective_to"),r.getBigDecimal("annual_ctc"),r.getString("revision_reason"),r.getString("created_by"),r.getTimestamp("created_at").toInstant());}
 private static LocalDate date(ResultSet r,String c)throws SQLException{var d=r.getDate(c);return d==null?null:d.toLocalDate();}
 private static void dates(LocalDate f,LocalDate t){if(t!=null&&t.isBefore(f))throw bad("Effective-to date cannot precede effective-from date");}
 private static UUID tenant(){return TenantContext.requireTenantId();}private static String norm(String v){return v.trim().toUpperCase(Locale.ROOT);}private static String blank(String v){return v==null||v.isBlank()?null:v.trim();}private static ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}private static ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}private static ResponseStatusException missing(String n){return new ResponseStatusException(HttpStatus.NOT_FOUND,n+" not found");}
}
