import {useCallback,useEffect,useMemo,useState,type FormEvent} from 'react'
import type {Session} from '@supabase/supabase-js'
import {Alert,Box,Button,Chip,CircularProgress,MenuItem,Paper,Stack,Tab,Table,TableBody,TableCell,TableHead,TableRow,Tabs,TextField,Typography} from '@mui/material'
import {apiJson,type TenantMembership} from './api'
type Employee={id:string;employeeNumber:string;firstName:string;lastName:string}
type LeaveType={id:string;code:string;name:string;annualEntitlement:number;accrualFrequency:string;minimumDays:number;maximumDays?:number;status:string}
type Balance={id:string;employmentId:string;leaveTypeId:string;leaveYear:number;openingBalance:number;accrued:number;used:number;available:number}
type Request={id:string;employmentId:string;leaveTypeId:string;startDate:string;endDate:string;requestedDays:number;reason:string;status:string}
const today=new Date().toISOString().slice(0,10),year=Number(today.slice(0,4)),admins=new Set(['SYSTEM_ADMIN','GROUP_ADMIN','COMPANY_ADMIN','HR_MANAGER','HR_EXECUTIVE'])
const blankType={code:'',name:'',paid:true,annualEntitlement:0,accrualFrequency:'ANNUAL',minimumDays:.5,maximumDays:'',halfDayAllowed:true,carryForwardLimit:0,negativeBalanceAllowed:false,supportingDocumentRequired:false,status:'ACTIVE'}
export default function LeaveAdmin({session,membership}:{session:Session;membership:TenantMembership}){
 const [tab,setTab]=useState<'requests'|'balances'|'types'>('requests'),[employees,setEmployees]=useState<Employee[]>([]),[types,setTypes]=useState<LeaveType[]>([]),[balances,setBalances]=useState<Balance[]>([]),[requests,setRequests]=useState<Request[]>([]),[typeForm,setTypeForm]=useState<Record<string,string|number|boolean>>(blankType),[typeId,setTypeId]=useState(''),[balance,setBalance]=useState({employmentId:'',leaveTypeId:'',leaveYear:year,openingBalance:0,accrued:0,adjusted:0}),[request,setRequest]=useState({employmentId:'',leaveTypeId:'',startDate:today,endDate:today,requestedDays:1,reason:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const admin=membership.roles.some(r=>admins.has(r)),names=useMemo(()=>new Map(employees.map(e=>[e.id,`${e.employeeNumber} - ${e.firstName} ${e.lastName}`])),[employees]),typeNames=useMemo(()=>new Map(types.map(t=>[t.id,`${t.code} - ${t.name}`])),[types])
 const load=useCallback(async()=>{setBusy(true);try{const [e,t,b,r]=await Promise.all([apiJson<Employee[]>('/employees?status=ACTIVE',session,membership.tenantId),apiJson<LeaveType[]>('/leave/types',session,membership.tenantId),apiJson<Balance[]>(`/leave/balances?year=${year}`,session,membership.tenantId),apiJson<Request[]>('/leave/requests',session,membership.tenantId)]);setEmployees(e);setTypes(t);setBalances(b);setRequests(r);setError('')}catch(e){setError(msg(e))}finally{setBusy(false)}},[membership.tenantId,session]);useEffect(()=>{void load()},[load])
 async function act(fn:()=>Promise<void>,text:string){setBusy(true);setError('');try{await fn();setNotice(text);await load()}catch(e){setError(msg(e))}finally{setBusy(false)}}
 async function submitRequest(e:FormEvent){e.preventDefault();await act(async()=>{await apiJson('/leave/requests',session,membership.tenantId,{method:'POST',body:JSON.stringify(request)});setRequest({...request,reason:''})},'Leave request submitted.')}
 async function saveBalance(e:FormEvent){e.preventDefault();await act(async()=>{await apiJson('/leave/balances',session,membership.tenantId,{method:'PUT',body:JSON.stringify(balance)})},'Balance saved.')}
 async function saveType(e:FormEvent){e.preventDefault();await act(async()=>{await apiJson(`/leave/types${typeId?`/${typeId}`:''}`,session,membership.tenantId,{method:typeId?'PUT':'POST',body:JSON.stringify({...typeForm,maximumDays:typeForm.maximumDays||null})});setTypeId('');setTypeForm(blankType)},'Leave type saved.')}
 async function decide(id:string,decision:string){await act(async()=>{await apiJson(`/leave/requests/${id}/decision`,session,membership.tenantId,{method:'POST',body:JSON.stringify({decision,comment:''})})},`Request ${decision.toLowerCase()}.`)}
 return <Stack spacing={3}><Paper><Tabs value={tab} onChange={(_e,v)=>setTab(v)}><Tab value="requests" label="Requests"/><Tab value="balances" label="Balances"/>{admin&&<Tab value="types" label="Leave types"/>}</Tabs></Paper>{error&&<Alert severity="error">{error}</Alert>}{notice&&<Alert severity="success">{notice}</Alert>}{busy&&<Box textAlign="center"><CircularProgress size={28}/></Box>}
 {tab==='requests'&&<Split table={<Table size="small"><TableHead><TableRow>{['Employee','Type','Dates / reason','Days','Status','Action'].map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{requests.map(r=><TableRow key={r.id}><TableCell>{names.get(r.employmentId)}</TableCell><TableCell>{typeNames.get(r.leaveTypeId)}</TableCell><TableCell>{r.startDate} to {r.endDate}<Typography variant="caption" display="block">{r.reason}</Typography></TableCell><TableCell>{r.requestedDays}</TableCell><TableCell><Chip size="small" label={label(r.status)}/></TableCell><TableCell>{admin&&r.status==='PENDING'&&<><Button size="small" onClick={()=>void decide(r.id,'APPROVED')}>Approve</Button><Button size="small" color="error" onClick={()=>void decide(r.id,'REJECTED')}>Reject</Button></>}</TableCell></TableRow>)}</TableBody></Table>} form={<Paper component="form" onSubmit={submitRequest} sx={{p:3}}><Typography variant="h6">New request</Typography><Stack spacing={2} mt={2}><EmployeeSelect value={request.employmentId} rows={employees} onChange={v=>setRequest({...request,employmentId:v})}/><TypeSelect value={request.leaveTypeId} rows={types} onChange={v=>setRequest({...request,leaveTypeId:v})}/><DateField label="Start" value={request.startDate} onChange={v=>setRequest({...request,startDate:v})}/><DateField label="End" value={request.endDate} onChange={v=>setRequest({...request,endDate:v})}/><TextField type="number" inputProps={{step:.5,min:.5}} label="Days" value={request.requestedDays} onChange={e=>setRequest({...request,requestedDays:Number(e.target.value)})}/><TextField required multiline label="Reason" value={request.reason} onChange={e=>setRequest({...request,reason:e.target.value})}/><Button type="submit" variant="contained">Submit</Button></Stack></Paper>}/>} 
 {tab==='balances'&&<Split table={<Table size="small"><TableHead><TableRow>{['Employee','Type','Year','Opening','Accrued','Used','Available'].map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{balances.map(b=><TableRow key={b.id}><TableCell>{names.get(b.employmentId)}</TableCell><TableCell>{typeNames.get(b.leaveTypeId)}</TableCell><TableCell>{b.leaveYear}</TableCell><TableCell>{b.openingBalance}</TableCell><TableCell>{b.accrued}</TableCell><TableCell>{b.used}</TableCell><TableCell>{b.available}</TableCell></TableRow>)}</TableBody></Table>} form={admin?<Paper component="form" onSubmit={saveBalance} sx={{p:3}}><Typography variant="h6">Set balance</Typography><Stack spacing={2} mt={2}><EmployeeSelect value={balance.employmentId} rows={employees} onChange={v=>setBalance({...balance,employmentId:v})}/><TypeSelect value={balance.leaveTypeId} rows={types} onChange={v=>setBalance({...balance,leaveTypeId:v})}/>{(['leaveYear','openingBalance','accrued','adjusted'] as const).map(k=><TextField key={k} type="number" label={label(k)} value={balance[k]} onChange={e=>setBalance({...balance,[k]:Number(e.target.value)})}/>)}<Button type="submit" variant="contained">Save</Button></Stack></Paper>:null}/>} 
 {tab==='types'&&admin&&<Split table={<Table size="small"><TableHead><TableRow>{['Code','Name','Entitlement','Accrual','Status'].map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{types.map(t=><TableRow hover key={t.id} onClick={()=>{setTypeId(t.id);setTypeForm({...t})}} sx={{cursor:'pointer'}}><TableCell>{t.code}</TableCell><TableCell>{t.name}</TableCell><TableCell>{t.annualEntitlement}</TableCell><TableCell>{label(t.accrualFrequency)}</TableCell><TableCell>{label(t.status)}</TableCell></TableRow>)}</TableBody></Table>} form={<Paper component="form" onSubmit={saveType} sx={{p:3}}><Typography variant="h6">{typeId?'Edit':'New'} leave type</Typography><Stack spacing={2} mt={2}>{['code','name'].map(k=><TextField required key={k} label={label(k)} value={typeForm[k] as string} onChange={e=>setTypeForm({...typeForm,[k]:e.target.value})}/>)}<TextField select label="Accrual" value={typeForm.accrualFrequency} onChange={e=>setTypeForm({...typeForm,accrualFrequency:e.target.value})}>{['MONTHLY','QUARTERLY','ANNUAL','NONE'].map(x=><MenuItem key={x} value={x}>{label(x)}</MenuItem>)}</TextField>{['annualEntitlement','minimumDays','maximumDays','carryForwardLimit'].map(k=><TextField key={k} type="number" inputProps={{step:.5}} label={label(k)} value={typeForm[k] as string|number} onChange={e=>setTypeForm({...typeForm,[k]:e.target.value===''?'':Number(e.target.value)})}/>)}{['paid','halfDayAllowed','negativeBalanceAllowed','supportingDocumentRequired'].map(k=><TextField select key={k} label={label(k)} value={String(typeForm[k])} onChange={e=>setTypeForm({...typeForm,[k]:e.target.value==='true'})}><MenuItem value="true">Yes</MenuItem><MenuItem value="false">No</MenuItem></TextField>)}<Button type="submit" variant="contained">Save</Button></Stack></Paper>}/>}</Stack>}
function Split({table,form}:{table:React.ReactNode;form:React.ReactNode}){return <Stack direction={{xs:'column',lg:'row'}} spacing={3} alignItems="flex-start"><Paper sx={{width:{xs:'100%',lg:'70%'},overflow:'auto'}}>{table}</Paper><Box sx={{width:{xs:'100%',lg:'30%'}}}>{form}</Box></Stack>}
function EmployeeSelect({value,rows,onChange}:{value:string;rows:Employee[];onChange:(v:string)=>void}){return <TextField select required label="Employee" value={value} onChange={e=>onChange(e.target.value)}>{rows.map(x=><MenuItem key={x.id} value={x.id}>{x.employeeNumber} - {x.firstName} {x.lastName}</MenuItem>)}</TextField>}
function TypeSelect({value,rows,onChange}:{value:string;rows:LeaveType[];onChange:(v:string)=>void}){return <TextField select required label="Leave type" value={value} onChange={e=>onChange(e.target.value)}>{rows.filter(x=>x.status==='ACTIVE').map(x=><MenuItem key={x.id} value={x.id}>{x.code} - {x.name}</MenuItem>)}</TextField>}
function DateField({label:caption,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <TextField type="date" required label={caption} value={value} onChange={e=>onChange(e.target.value)} InputLabelProps={{shrink:true}}/>}function label(v:string){return v.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ').toLowerCase().replace(/^./,c=>c.toUpperCase())}function msg(e:unknown){return e instanceof Error?e.message:'Operation failed.'}
