import {useCallback,useEffect,useMemo,useState,type FormEvent} from 'react'
import type {Session} from '@supabase/supabase-js'
import {Alert,Box,Button,Checkbox,CircularProgress,FormControlLabel,MenuItem,Paper,Stack,Tab,Table,TableBody,TableCell,TableHead,TableRow,Tabs,TextField,Typography} from '@mui/material'
import {apiJson,type TenantMembership} from './api'
type Employee={id:string;employeeNumber:string;firstName:string;lastName:string}
type Component={id:string;code:string;name:string;componentType:string;calculationType:string;calculationBaseCode?:string;defaultValue:number;taxable:boolean;pfApplicable:boolean;esiApplicable:boolean;prorated:boolean;includedInGross:boolean;includedInCtc:boolean;includedInNet:boolean;roundingScale:number;effectiveFrom:string;effectiveTo?:string;status:string}
type Line={salaryComponentId:string;sequenceNumber:number;value:number;formulaExpression:string}
type Structure={id:string;code:string;name:string;description?:string;effectiveFrom:string;effectiveTo?:string;status:string;components:Line[]}
type Assignment={id:string;employmentId:string;salaryStructureId:string;effectiveFrom:string;effectiveTo?:string;annualCtc:number;revisionReason:string}
const today=new Date().toISOString().slice(0,10)
const blankComponent={code:'',name:'',componentType:'EARNING',calculationType:'FIXED',calculationBaseCode:'',defaultValue:0,taxable:true,pfApplicable:false,esiApplicable:false,prorated:true,includedInGross:true,includedInCtc:true,includedInNet:true,roundingScale:2,effectiveFrom:today,effectiveTo:'',status:'ACTIVE'}
export default function PayrollStructureAdmin({session,membership}:{session:Session;membership:TenantMembership}){
 const [tab,setTab]=useState<'components'|'structures'|'assignments'|'settings'>('components'),[components,setComponents]=useState<Component[]>([]),[structures,setStructures]=useState<Structure[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[componentId,setComponentId]=useState(''),[componentForm,setComponentForm]=useState<Record<string,string|number|boolean>>(blankComponent),[structureId,setStructureId]=useState(''),[structureForm,setStructureForm]=useState({code:'',name:'',description:'',effectiveFrom:today,effectiveTo:'',status:'DRAFT'}),[lines,setLines]=useState<Line[]>([]),[assignment,setAssignment]=useState({employmentId:'',salaryStructureId:'',effectiveFrom:today,effectiveTo:'',annualCtc:0,revisionReason:''}),[settings,setSettings]=useState({payFrequency:'MONTHLY',attendanceCutoffDay:25,paymentDay:7,workingDayBasis:'CALENDAR_DAYS',roundingScale:2,negativeSalaryPolicy:'HOLD'}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const load=useCallback(async()=>{setBusy(true);try{const [c,s,e,p]=await Promise.all([apiJson<Component[]>('/payroll/structure/components',session,membership.tenantId),apiJson<Structure[]>('/payroll/structure/templates',session,membership.tenantId),apiJson<Employee[]>('/employees?status=ACTIVE',session,membership.tenantId),apiJson<typeof settings>('/payroll/structure/settings',session,membership.tenantId)]);setComponents(c);setStructures(s);setEmployees(e);setSettings(p);setError('')}catch(e){setError(message(e))}finally{setBusy(false)}},[membership.tenantId,session]);useEffect(()=>{void load()},[load])
 const employeeNames=useMemo(()=>new Map(employees.map(e=>[e.id,`${e.employeeNumber} - ${e.firstName} ${e.lastName}`])),[employees]),structureNames=useMemo(()=>new Map(structures.map(s=>[s.id,`${s.code} - ${s.name}`])),[structures])
 async function act(fn:()=>Promise<void>,text:string){setBusy(true);setError('');try{await fn();setNotice(text);await load()}catch(e){setError(message(e))}finally{setBusy(false)}}
 async function saveComponent(e:FormEvent){e.preventDefault();await act(async()=>{await apiJson(`/payroll/structure/components${componentId?`/${componentId}`:''}`,session,membership.tenantId,{method:componentId?'PUT':'POST',body:JSON.stringify({...componentForm,calculationBaseCode:componentForm.calculationBaseCode||null,effectiveTo:componentForm.effectiveTo||null})});setComponentId('');setComponentForm(blankComponent)},'Salary component saved.')}
 async function saveStructure(e:FormEvent){e.preventDefault();if(!lines.length){setError('Add at least one component.');return}await act(async()=>{await apiJson(`/payroll/structure/templates${structureId?`/${structureId}`:''}`,session,membership.tenantId,{method:structureId?'PUT':'POST',body:JSON.stringify({...structureForm,effectiveTo:structureForm.effectiveTo||null,components:lines.map((x,i)=>({...x,sequenceNumber:i+1,formulaExpression:x.formulaExpression||null}))})});setStructureId('');setLines([])},'Salary structure saved.')}
 async function saveAssignment(e:FormEvent){e.preventDefault();await act(async()=>{await apiJson('/payroll/structure/assignments',session,membership.tenantId,{method:'POST',body:JSON.stringify({...assignment,effectiveTo:assignment.effectiveTo||null})});setAssignments(await apiJson<Assignment[]>(`/payroll/structure/assignments?employmentId=${assignment.employmentId}`,session,membership.tenantId))},'Salary revision assigned.')}
 async function loadAssignments(id:string){setAssignment({...assignment,employmentId:id});if(id)setAssignments(await apiJson<Assignment[]>(`/payroll/structure/assignments?employmentId=${id}`,session,membership.tenantId))}
 async function saveSettings(e:FormEvent){e.preventDefault();await act(async()=>{await apiJson('/payroll/structure/settings',session,membership.tenantId,{method:'PUT',body:JSON.stringify(settings)})},'Payroll settings saved.')}
 function addLine(id:string){if(id&&!lines.some(x=>x.salaryComponentId===id)){const c=components.find(x=>x.id===id)!;setLines([...lines,{salaryComponentId:id,sequenceNumber:lines.length+1,value:c.defaultValue,formulaExpression:''}])}}
 return <Stack spacing={3}>{error&&<Alert severity="error">{error}</Alert>}{notice&&<Alert severity="success">{notice}</Alert>}{busy&&<Box textAlign="center"><CircularProgress size={26}/></Box>}<Paper><Tabs value={tab} onChange={(_e,v)=>setTab(v)} variant="scrollable"><Tab value="components" label="Components"/><Tab value="structures" label="Structures"/><Tab value="assignments" label="Employee salaries"/><Tab value="settings" label="Payroll settings"/></Tabs></Paper>
 {tab==='components'&&<Split left={<Table size="small"><TableHead><TableRow>{['Code','Name','Type','Calculation','Default','Effective'].map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{components.map(c=><TableRow hover key={c.id} sx={{cursor:'pointer'}} onClick={()=>{setComponentId(c.id);setComponentForm({...c,effectiveTo:c.effectiveTo??'',calculationBaseCode:c.calculationBaseCode??''})}}><TableCell>{c.code}</TableCell><TableCell>{c.name}</TableCell><TableCell>{label(c.componentType)}</TableCell><TableCell>{label(c.calculationType)}</TableCell><TableCell>{c.defaultValue}</TableCell><TableCell>{c.effectiveFrom}</TableCell></TableRow>)}</TableBody></Table>} right={<Paper component="form" onSubmit={saveComponent} sx={{p:3}}><Typography variant="h6">{componentId?'Edit':'New'} component</Typography><Stack spacing={2} mt={2}><TextField required label="Code" value={componentForm.code} onChange={e=>setComponentForm({...componentForm,code:e.target.value})}/><TextField required label="Name" value={componentForm.name} onChange={e=>setComponentForm({...componentForm,name:e.target.value})}/><Choice label="Component type" value={componentForm.componentType} values={['EARNING','DEDUCTION','EMPLOYER_CONTRIBUTION']} onChange={v=>setComponentForm({...componentForm,componentType:v})}/><Choice label="Calculation" value={componentForm.calculationType} values={['FIXED','PERCENTAGE','FORMULA']} onChange={v=>setComponentForm({...componentForm,calculationType:v})}/><TextField label="Calculation base code" value={componentForm.calculationBaseCode} onChange={e=>setComponentForm({...componentForm,calculationBaseCode:e.target.value})}/><TextField type="number" label="Default value" value={componentForm.defaultValue} onChange={e=>setComponentForm({...componentForm,defaultValue:Number(e.target.value)})}/><DatePair form={componentForm} set={setComponentForm}/><Box>{['taxable','pfApplicable','esiApplicable','prorated','includedInGross','includedInCtc','includedInNet'].map(k=><FormControlLabel key={k} control={<Checkbox checked={Boolean(componentForm[k])} onChange={e=>setComponentForm({...componentForm,[k]:e.target.checked})}/>} label={label(k)}/>)}</Box><Button type="submit" variant="contained">Save component</Button></Stack></Paper>}/>} 
 {tab==='structures'&&<Split left={<Table size="small"><TableHead><TableRow>{['Code','Name','Components','Effective','Status'].map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{structures.map(s=><TableRow hover key={s.id} sx={{cursor:'pointer'}} onClick={()=>{setStructureId(s.id);setStructureForm({...s,description:s.description??'',effectiveTo:s.effectiveTo??''});setLines(s.components)}}><TableCell>{s.code}</TableCell><TableCell>{s.name}</TableCell><TableCell>{s.components.length}</TableCell><TableCell>{s.effectiveFrom}</TableCell><TableCell>{label(s.status)}</TableCell></TableRow>)}</TableBody></Table>} right={<Paper component="form" onSubmit={saveStructure} sx={{p:3}}><Typography variant="h6">{structureId?'Edit':'New'} structure</Typography><Stack spacing={2} mt={2}>{['code','name','description'].map(k=><TextField key={k} required={k!=='description'} label={label(k)} value={structureForm[k as keyof typeof structureForm]} onChange={e=>setStructureForm({...structureForm,[k]:e.target.value})}/>)}<DatePair form={structureForm} set={setStructureForm}/><Choice label="Status" value={structureForm.status} values={['DRAFT','ACTIVE','INACTIVE']} onChange={v=>setStructureForm({...structureForm,status:v})}/><Choice label="Add component" value="" values={components.filter(c=>c.status==='ACTIVE').map(c=>c.id)} display={id=>components.find(c=>c.id===id)?.name??'Select'} onChange={addLine}/>{lines.map((line,i)=><Stack direction="row" spacing={1} key={line.salaryComponentId}><TextField fullWidth label={components.find(c=>c.id===line.salaryComponentId)?.name} type="number" value={line.value} onChange={e=>setLines(lines.map((x,n)=>n===i?{...x,value:Number(e.target.value)}:x))}/><Button color="error" onClick={()=>setLines(lines.filter((_,n)=>n!==i))}>Remove</Button></Stack>)}<Button type="submit" variant="contained">Save structure</Button></Stack></Paper>}/>} 
 {tab==='assignments'&&<Split left={<Table size="small"><TableHead><TableRow>{['Employee','Structure','Annual CTC','Effective','Reason'].map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{assignments.map(a=><TableRow key={a.id}><TableCell>{employeeNames.get(a.employmentId)}</TableCell><TableCell>{structureNames.get(a.salaryStructureId)}</TableCell><TableCell>{Number(a.annualCtc).toLocaleString('en-IN')}</TableCell><TableCell>{a.effectiveFrom}</TableCell><TableCell>{a.revisionReason}</TableCell></TableRow>)}</TableBody></Table>} right={<Paper component="form" onSubmit={saveAssignment} sx={{p:3}}><Typography variant="h6">Assign / revise salary</Typography><Stack spacing={2} mt={2}><Choice label="Employee" value={assignment.employmentId} values={employees.map(e=>e.id)} display={id=>employeeNames.get(id)??''} onChange={v=>void loadAssignments(v)}/><Choice label="Salary structure" value={assignment.salaryStructureId} values={structures.filter(s=>s.status==='ACTIVE').map(s=>s.id)} display={id=>structureNames.get(id)??''} onChange={v=>setAssignment({...assignment,salaryStructureId:v})}/><TextField required type="number" label="Annual CTC" value={assignment.annualCtc} onChange={e=>setAssignment({...assignment,annualCtc:Number(e.target.value)})}/><TextField required type="date" label="Effective from" value={assignment.effectiveFrom} onChange={e=>setAssignment({...assignment,effectiveFrom:e.target.value})} InputLabelProps={{shrink:true}}/><TextField label="Revision reason" required value={assignment.revisionReason} onChange={e=>setAssignment({...assignment,revisionReason:e.target.value})}/><Button type="submit" variant="contained">Assign salary</Button></Stack></Paper>}/>} 
 {tab==='settings'&&<Paper component="form" onSubmit={saveSettings} sx={{p:3,maxWidth:600}}><Typography variant="h6">Company payroll settings</Typography><Stack spacing={2} mt={2}><Choice label="Working-day basis" value={settings.workingDayBasis} values={['CALENDAR_DAYS','FIXED_30','PAYABLE_DAYS']} onChange={v=>setSettings({...settings,workingDayBasis:v})}/><TextField type="number" label="Attendance cutoff day" value={settings.attendanceCutoffDay} onChange={e=>setSettings({...settings,attendanceCutoffDay:Number(e.target.value)})}/><TextField type="number" label="Payment day" value={settings.paymentDay} onChange={e=>setSettings({...settings,paymentDay:Number(e.target.value)})}/><Choice label="Negative salary policy" value={settings.negativeSalaryPolicy} values={['HOLD','ZERO','ALLOW']} onChange={v=>setSettings({...settings,negativeSalaryPolicy:v})}/><Button type="submit" variant="contained">Save settings</Button></Stack></Paper>}</Stack>}
function Split({left,right}:{left:React.ReactNode;right:React.ReactNode}){return <Stack direction={{xs:'column',lg:'row'}} spacing={3} alignItems="flex-start"><Paper sx={{width:{xs:'100%',lg:'64%'},overflow:'auto'}}>{left}</Paper><Box sx={{width:{xs:'100%',lg:'36%'}}}>{right}</Box></Stack>}
function Choice({label:caption,value,values,onChange,display=(v)=>label(v)}:{label:string;value:string|number|boolean;values:string[];onChange:(v:string)=>void;display?:(v:string)=>string}){return <TextField select label={caption} value={value} onChange={e=>onChange(e.target.value)}>{values.map(v=><MenuItem key={v} value={v}>{display(v)}</MenuItem>)}</TextField>}
function DatePair({form,set}:{form:Record<string,unknown>;set:(v:any)=>void}){return <Stack direction="row" spacing={1}><TextField fullWidth required type="date" label="Effective from" value={form.effectiveFrom} onChange={e=>set({...form,effectiveFrom:e.target.value})} InputLabelProps={{shrink:true}}/><TextField fullWidth type="date" label="Effective to" value={form.effectiveTo} onChange={e=>set({...form,effectiveTo:e.target.value})} InputLabelProps={{shrink:true}}/></Stack>}
function label(v:string){return v.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ').toLowerCase().replace(/^./,c=>c.toUpperCase())}function message(e:unknown){return e instanceof Error?e.message:'Operation failed.'}
