import LeaveApprovals from './LeaveApprovals'
import {useEffect,useMemo,useState,type FormEvent} from 'react'
import type {Session} from '@supabase/supabase-js'
import {Alert,Box,Button,CircularProgress,Stack,TextField,Typography} from '@mui/material'
import {loadTenantMemberships,type TenantMembership} from './api'
import {supabase,supabaseConfigurationMissing} from './supabase'
import OrganizationAdmin from './OrganizationAdmin'
import EmployeeAdmin from './EmployeeAdmin'
import AttendanceAdmin from './AttendanceAdmin'
import LeaveAdmin from './LeaveAdmin'
import EmployeeSelfService from './EmployeeSelfService'
import Reports, {LiveDashboard} from './Reports'
import FinancialRequests from './FinancialRequests'
import HrWorkflows from './HrWorkflows'
import PayrollStructureAdmin from './PayrollStructureAdmin'
import AccountAdmin from './AccountAdmin'
import './workforce.css'
type Module='approvals'|'workflows'|'finance'|'reports'|'self'|'dashboard'|'organization'|'employees'|'attendance'|'leave'|'payroll'|'accounts'
const ACTIVE='erp.activeTenantId'
const nav:[string,{label:string,module?:Module}[]][]=[['Workforce',[{label:'My Leave & Payslips',module:'self'},{label:'Leave Approvals & Notifications',module:'approvals'},{label:'Dashboard',module:'dashboard'},{label:'Employee Master',module:'employees'},{label:'Attendance & Muster',module:'attendance'},{label:'Leave Management',module:'leave'},{label:'Salary & Payroll',module:'payroll'},{label:'Expenses, Loans & Advances',module:'finance'},{label:'HR Workflows & Exit',module:'workflows'}]],['Compliance',[{label:'PF / ESIC / PT'},{label:'CLRA & Licences'},{label:'Data Quality'}]],['Setup',[{label:'Organisation Masters',module:'organization'},{label:'Account Administration',module:'accounts'},{label:'Reports & Exports',module:'reports'}]]]
export default function WorkforceApp(){
 const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[memberships,setMemberships]=useState<TenantMembership[]>([]),[tenant,setTenant]=useState(localStorage.getItem(ACTIVE)??''),[module,setModule]=useState<Module>('dashboard'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[needsPassword,setNeedsPassword]=useState(()=>/[#&](type=invite|type=recovery)(&|$)/.test(window.location.hash)),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(!supabase){setLoading(false);return}void supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[])
 useEffect(()=>{if(!session){setMemberships([]);return}setBusy(true);void loadTenantMemberships(session).then(items=>{setMemberships(items);const next=items.some(x=>x.tenantId===tenant)?tenant:items[0]?.tenantId??'';setTenant(next);if(next)localStorage.setItem(ACTIVE,next)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load company access.')).finally(()=>setBusy(false))},[session])
 const membership=useMemo(()=>memberships.find(x=>x.tenantId===tenant),[memberships,tenant]),canView=membership?.roles.some(r=>['SYSTEM_ADMIN','GROUP_ADMIN','COMPANY_ADMIN','HR_MANAGER','PAYROLL_MANAGER'].includes(r))??false,canManageAccounts=membership?.roles.some(r=>['SYSTEM_ADMIN','GROUP_ADMIN','COMPANY_ADMIN'].includes(r))??false
 async function signIn(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError('');const {error:problem}=await supabase.auth.signInWithPassword({email,password});if(problem)setError(problem.message);setBusy(false)}
 async function establishPassword(e:FormEvent){e.preventDefault();if(!supabase)return;if(newPassword.length<8){setError('Password must contain at least 8 characters.');return}if(newPassword!==confirmPassword){setError('Passwords do not match.');return}setBusy(true);setError('');const {error:problem}=await supabase.auth.updateUser({password:newPassword});if(problem)setError(problem.message);else{setNeedsPassword(false);setNewPassword('');setConfirmPassword('');history.replaceState(null,'',location.pathname+location.search)}setBusy(false)}
 if(loading)return <Box minHeight="100vh" display="grid" sx={{placeItems:'center'}}><CircularProgress/></Box>
 if(supabaseConfigurationMissing)return <Box p={5}><Alert severity="error">Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.</Alert></Box>
 if(!session)return <div className="wf-login"><div className="wf-login-brand"><div><div className="wf-mark">AGERP</div><div className="wf-sub">AMAR GROUP ERP</div><h1>Workforce<br/>Command Center</h1><p>One source of truth for people, attendance, leave and payroll across every company.</p></div><small>Amar Fibrotech Â· Econfra Â· Ampar Technova</small></div><div className="wf-login-form"><form className="wf-login-card" onSubmit={signIn}><Typography variant="h5" fontWeight={700}>Welcome back</Typography><Typography color="text.secondary" mb={3}>Sign in to your organisation account.</Typography><Stack spacing={2}>{error&&<Alert severity="error">{error}</Alert>}<TextField label="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><TextField label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><Button type="submit" variant="contained" disabled={busy}>Sign in</Button></Stack></form></div></div>
 if(needsPassword)return <div className="wf-login"><div className="wf-login-brand"><div><div className="wf-mark">AGERP</div><div className="wf-sub">AMAR GROUP ERP</div><h1>Activate your<br/>account</h1><p>Create a password to finish accepting your invitation.</p></div></div><div className="wf-login-form"><form className="wf-login-card" onSubmit={establishPassword}><Typography variant="h5" fontWeight={700}>Set your password</Typography><Stack spacing={2} mt={3}>{error&&<Alert severity="error">{error}</Alert>}<TextField label="New password" type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} required/><TextField label="Confirm password" type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required/><Button type="submit" variant="contained" disabled={busy}>Activate account</Button></Stack></form></div></div>
 const title={approvals:'Leave Approvals & Notifications',workflows:'HR Workflows & Exit',finance:'Expenses, Loans & Advances',reports:'Reports & Exports',self:'My Leave & Payslips',dashboard:'Workforce Dashboard',organization:'Organisation Masters',employees:'Employee Master',attendance:'Attendance & Muster',leave:'Leave Management',payroll:'Salary & Payroll',accounts:'Account Administration'}[module]
 return <div className="wf-shell"><aside className="wf-sidebar"><div className="wf-brand"><div className="wf-mark">AGERP</div><div className="wf-sub">Amar Group ERP</div></div>{nav.map(([group,items])=><nav className="wf-nav" key={group}><div className="wf-nav-label">{group}</div>{items.map(item=><button key={item.label} disabled={!item.module||(item.module==='accounts'?!canManageAccounts:(item.module!=='approvals'&&item.module!=='finance'&&item.module!=='self'&&item.module!=='dashboard'&&item.module!=='organization'&&!canView))} className={`wf-nav-item ${item.module===module?'active':''}`} onClick={()=>item.module&&setModule(item.module)}>{item.label}</button>)}</nav>)}<div className="wf-side-foot">Companies<br/><span>{memberships.map(x=>x.legalName).join(' Â· ')||'No company access'}</span></div></aside><main className="wf-main"><header className="wf-topbar"><div><h1>{title}</h1><div className="wf-crumb">HR & Attendance module Â· live multi-company workspace</div></div><div className="wf-tools">{memberships.length>0&&<select className="wf-company" value={tenant} onChange={e=>{setTenant(e.target.value);localStorage.setItem(ACTIVE,e.target.value)}}>{memberships.map(x=><option key={x.tenantId} value={x.tenantId}>{x.legalName}</option>)}</select>}<span className="wf-role">{membership?.roles[0]?.replaceAll('_',' ')??'No role'}</span><button className="wf-signout" onClick={()=>void supabase?.auth.signOut()}>Sign out</button></div></header><div className="wf-content">{error&&<Alert severity="error">{error}</Alert>}{busy&&<CircularProgress size={26}/>} {membership&&<div className="wf-module" key={`${session.user.id}:${membership.tenantId}`}>{module==='approvals'&&<LeaveApprovals session={session} membership={membership}/>} {module==='workflows'&&canView&&<HrWorkflows session={session} membership={membership}/>} {module==='finance'&&<FinancialRequests session={session} membership={membership}/>} {module==='self'&&<EmployeeSelfService session={session} membership={membership}/>}{module==='dashboard'&&(canView?<LiveDashboard session={session} membership={membership}/>:<EmployeeSelfService session={session} membership={membership}/>)}{module==='reports'&&canView&&<Reports session={session} membership={membership}/>}{module==='organization'&&<OrganizationAdmin session={session} membership={membership}/>} {module==='accounts'&&canManageAccounts&&<AccountAdmin session={session} membership={membership}/>} {module==='employees'&&canView&&<EmployeeAdmin session={session} membership={membership}/>} {module==='attendance'&&canView&&<AttendanceAdmin session={session} membership={membership}/>} {module==='leave'&&canView&&<LeaveAdmin session={session} membership={membership}/>} {module==='payroll'&&canView&&<PayrollStructureAdmin session={session} membership={membership}/>}</div>}</div></main></div>
}
