import {useEffect,useMemo,useState,type FormEvent} from 'react'
import type {Session} from '@supabase/supabase-js'
import {Alert,Box,Button,CircularProgress,Stack,TextField,Typography} from '@mui/material'
import {loadTenantMemberships,type TenantMembership} from './api'
import {supabase,supabaseConfigurationMissing} from './supabase'
import OrganizationAdmin from './OrganizationAdmin'
import EmployeeAdmin from './EmployeeAdmin'
import AttendanceAdmin from './AttendanceAdmin'
import LeaveAdmin from './LeaveAdmin'
import './workforce.css'
type Module='dashboard'|'organization'|'employees'|'attendance'|'leave'
const ACTIVE='erp.activeTenantId'
const nav:[string,{label:string,module?:Module}[]][]=[['Workforce',[{label:'Dashboard',module:'dashboard'},{label:'Employee Master',module:'employees'},{label:'Attendance & Muster',module:'attendance'},{label:'Leave Management',module:'leave'},{label:'Payroll Runs'},{label:'Advances & Loans'},{label:'Exit / F&F'}]],['Compliance',[{label:'PF / ESIC / PT'},{label:'CLRA & Licences'},{label:'Data Quality'}]],['Setup',[{label:'Organisation Masters',module:'organization'},{label:'Reports & Exports'}]]]
export default function WorkforceApp(){
 const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[memberships,setMemberships]=useState<TenantMembership[]>([]),[tenant,setTenant]=useState(localStorage.getItem(ACTIVE)??''),[module,setModule]=useState<Module>('dashboard'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(!supabase){setLoading(false);return}void supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[])
 useEffect(()=>{if(!session){setMemberships([]);return}setBusy(true);void loadTenantMemberships(session).then(items=>{setMemberships(items);const next=items.some(x=>x.tenantId===tenant)?tenant:items[0]?.tenantId??'';setTenant(next);if(next)localStorage.setItem(ACTIVE,next)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load company access.')).finally(()=>setBusy(false))},[session])
 const membership=useMemo(()=>memberships.find(x=>x.tenantId===tenant),[memberships,tenant]),canView=membership?.roles.some(r=>['SYSTEM_ADMIN','GROUP_ADMIN','COMPANY_ADMIN','HR_MANAGER','PAYROLL_MANAGER'].includes(r))??false
 async function signIn(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError('');const {error:problem}=await supabase.auth.signInWithPassword({email,password});if(problem)setError(problem.message);setBusy(false)}
 if(loading)return <Box minHeight="100vh" display="grid" sx={{placeItems:'center'}}><CircularProgress/></Box>
 if(supabaseConfigurationMissing)return <Box p={5}><Alert severity="error">Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.</Alert></Box>
 if(!session)return <div className="wf-login"><div className="wf-login-brand"><div><div className="wf-mark">AGERP</div><div className="wf-sub">AMAR GROUP ERP</div><h1>Workforce<br/>Command Center</h1><p>One source of truth for people, attendance, leave and payroll across every company.</p></div><small>Amar Fibrotech · Econfra · Ampar Technova</small></div><div className="wf-login-form"><form className="wf-login-card" onSubmit={signIn}><Typography variant="h5" fontWeight={700}>Welcome back</Typography><Typography color="text.secondary" mb={3}>Sign in to your organisation account.</Typography><Stack spacing={2}>{error&&<Alert severity="error">{error}</Alert>}<TextField label="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><TextField label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><Button type="submit" variant="contained" disabled={busy}>Sign in</Button></Stack></form></div></div>
 const title={dashboard:'Workforce Dashboard',organization:'Organisation Masters',employees:'Employee Master',attendance:'Attendance & Muster',leave:'Leave Management'}[module]
 return <div className="wf-shell"><aside className="wf-sidebar"><div className="wf-brand"><div className="wf-mark">AGERP</div><div className="wf-sub">Amar Group ERP</div></div>{nav.map(([group,items])=><nav className="wf-nav" key={group}><div className="wf-nav-label">{group}</div>{items.map(item=><button key={item.label} disabled={!item.module||(item.module!=='dashboard'&&item.module!=='organization'&&!canView)} className={`wf-nav-item ${item.module===module?'active':''}`} onClick={()=>item.module&&setModule(item.module)}>{item.label}</button>)}</nav>)}<div className="wf-side-foot">Companies<br/><span>{memberships.map(x=>x.legalName).join(' · ')||'No company access'}</span></div></aside><main className="wf-main"><header className="wf-topbar"><div><h1>{title}</h1><div className="wf-crumb">HR & Attendance module · live multi-company workspace</div></div><div className="wf-tools">{memberships.length>0&&<select className="wf-company" value={tenant} onChange={e=>{setTenant(e.target.value);localStorage.setItem(ACTIVE,e.target.value)}}>{memberships.map(x=><option key={x.tenantId} value={x.tenantId}>{x.legalName}</option>)}</select>}<span className="wf-role">{membership?.roles[0]?.replaceAll('_',' ')??'No role'}</span><button className="wf-signout" onClick={()=>void supabase?.auth.signOut()}>Sign out</button></div></header><div className="wf-content">{error&&<Alert severity="error">{error}</Alert>}{busy&&<CircularProgress size={26}/>} {membership&&<div className="wf-module">{module==='dashboard'&&<Dashboard/>}{module==='organization'&&<OrganizationAdmin session={session} membership={membership}/>} {module==='employees'&&canView&&<EmployeeAdmin session={session} membership={membership}/>} {module==='attendance'&&canView&&<AttendanceAdmin session={session} membership={membership}/>} {module==='leave'&&canView&&<LeaveAdmin session={session} membership={membership}/>}</div>}</div></main></div>
}
function Dashboard(){const bars=[[42,66],[36,62],[40,72],[42,78]],months=['Apr','May','Jun','Jul'];return <><div className="wf-kpis">{[['Active workforce (Jul)','120','+8 vs Jun','up'],['Joiners (Apr–Jul)','41','confirmed after audit',''],['Exits (Apr–Jul)','37','no formal exit date on file','down'],['July payout','₹28,18,157','+19.7% vs Jun','up'],['Missing employee code','62 / 120','52% of active workforce','down']].map(x=><div className="wf-kpi" key={x[0]}><div className="wf-label">{x[0]}</div><div className="wf-value">{x[1]}</div><div className={`wf-delta ${x[3]}`}>{x[2]}</div></div>)}</div><div className="wf-dashboard-grid"><div className="wf-col"><section className="wf-card"><div className="wf-card-head"><div><div className="wf-card-title">Headcount by company</div><div className="wf-card-sub">Active workers on the monthly wage sheet, Apr–Jul 2026</div></div><div className="wf-legend"><span><i className="wf-swatch" style={{background:'#2A78D6'}}/>Econfra</span><span><i className="wf-swatch" style={{background:'#EB6834'}}/>Amar Fibrotech</span></div></div><div className="wf-bars">{bars.map((b,i)=><div className="wf-bar-group" key={months[i]}><div className="wf-bar a" style={{height:`${b[0]}%`}}/><div className="wf-bar b" style={{height:`${b[1]}%`}}/><span className="wf-bar-label">{months[i]} '26</span></div>)}</div></section><section className="wf-card"><div className="wf-card-title">Workforce distribution by site</div><div className="wf-card-sub">July 2026 deployment snapshot across active client sites</div><SiteRows/></section></div><div className="wf-col"><section className="wf-card"><div className="wf-card-title">Data quality & governance</div><div className="wf-card-sub">What today's spreadsheets reveal about master-data readiness</div>{['62 of 120 active workers have no permanent employee code.','67 of 120 active workers have no record in the official HR master.','380 Active codes group-wide against 120 people paid in July.','PF/UAN number missing for 55% of employees.'].map(t=><div className="wf-alert" key={t}><i className="wf-dot"/><span><b className="wf-chip">critical</b>{t}</span></div>)}</section><section className="wf-card"><div className="wf-card-title">Implementation status</div><div className="wf-card-sub">Core modules available in this workspace</div><SiteRows status/></section></div></div></>}
function SiteRows({status=false}:{status?:boolean}){const rows=status?[['Organisation masters','Ready'],['Employee master','Ready'],['Attendance & muster','Ready'],['Leave management','Ready'],['Payroll','Next phase']]:[['Shiva','24'],['Epigral','21'],['Navin Fluorine','20'],['Aarti — Zone 4','8'],['SRF','9']];return <table style={{width:'100%',borderCollapse:'collapse',marginTop:12,fontSize:13}}><tbody>{rows.map(r=><tr key={r[0]}><td style={{padding:'9px 10px',borderBottom:'1px solid var(--line)',color:'var(--ink-secondary)'}}>{r[0]}</td><td style={{padding:'9px 10px',borderBottom:'1px solid var(--line)',fontFamily:'IBM Plex Mono',textAlign:'right'}}>{r[1]}</td></tr>)}</tbody></table>}
