spring:
  application:
    name: multitenant-erp-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/multitenant_erp}
    username: ${DB_USERNAME:erp}
    password: ${DB_PASSWORD:erp_local_only}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  error:
    include-message: always
