package com.multitenanterp.payroll;
import com.multitenanterp.platform.tenant.TenantContext;import org.h2.jdbcx.JdbcDataSource;import org.junit.jupiter.api.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.web.server.ResponseStatusException;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;import static org.assertj.core.api.Assertions.*;
class SalaryStructureServiceIntegrationTest{
 private JdbcClient db;private SalaryStructureService service;private UUID tenantA,tenantB,employeeA;
 @BeforeEach void setup(){tenantA=UUID.randomUUID();tenantB=UUID.randomUUID();employeeA=UUID.randomUUID();JdbcDataSource ds=new JdbcDataSource();ds.setURL("jdbc:h2:mem:"+UUID.randomUUID()+";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");db=JdbcClient.create(ds);schema();db.sql("INSERT INTO tenant VALUES(?),(?)").params(tenantA,tenantB).update();db.sql("INSERT INTO employment VALUES(?,?),(?,?)").params(employeeA,tenantA,UUID.randomUUID(),tenantB).update();service=new SalaryStructureService(db);TenantContext.set(tenantA);}
 @AfterEach void clear(){TenantContext.clear();}
 @Test void componentStructureAndRevisionAreEffectiveDated(){SalaryComponent basic=service.saveComponent(null,component("BASIC"));SalaryStructure structure=service.saveStructure(null,new SaveSalaryStructureRequest("STAFF","Staff salary",null,LocalDate.of(2026,1,1),null,"ACTIVE",List.of(new SaveSalaryStructureLineRequest(basic.id(),1,new BigDecimal("25000"),null))));EmployeeSalaryAssignment assignment=service.assign(new SaveEmployeeSalaryAssignmentRequest(employeeA,structure.id(),LocalDate.of(2026,9,1),null,new BigDecimal("480000"),"Annual revision"),"payroll@example.com");assertThat(assignment.annualCtc()).isEqualByComparingTo("480000");assertThat(service.structures().getFirst().components()).hasSize(1);}
 @Test void tenantCannotSeeOrReferenceAnotherCompanySalaryData(){SalaryComponent basic=service.saveComponent(null,component("BASIC"));TenantContext.set(tenantB);assertThat(service.components()).isEmpty();assertThat(service.structures()).isEmpty();assertThatThrownBy(()->service.saveStructure(null,new SaveSalaryStructureRequest("BAD","Cross company",null,LocalDate.of(2026,1,1),null,"ACTIVE",List.of(new SaveSalaryStructureLineRequest(basic.id(),1,BigDecimal.ONE,null))))).isInstanceOf(ResponseStatusException.class);}
 @Test void validatesDatesAndCalculationBase(){assertThatThrownBy(()->service.saveComponent(null,new SaveSalaryComponentRequest("HRA","HRA","EARNING","PERCENTAGE",null,new BigDecimal("40"),true,false,false,true,true,true,true,2,LocalDate.of(2026,1,1),null,"ACTIVE"))).isInstanceOf(ResponseStatusException.class);}
 private SaveSalaryComponentRequest component(String code){return new SaveSalaryComponentRequest(code,"Basic salary","EARNING","FIXED",null,new BigDecimal("25000"),true,true,false,true,true,true,true,2,LocalDate.of(2026,1,1),null,"ACTIVE");}
 private void schema(){db.sql("CREATE TABLE tenant(id UUID PRIMARY KEY)").update();db.sql("CREATE TABLE employment(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,UNIQUE(id,tenant_id))").update();db.sql("CREATE TABLE payroll_setting(tenant_id UUID PRIMARY KEY,pay_frequency VARCHAR(20),attendance_cutoff_day INT,payment_day INT,working_day_basis VARCHAR(20),rounding_scale INT,negative_salary_policy VARCHAR(20),updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)").update();db.sql("CREATE TABLE salary_component(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,code VARCHAR(40),name VARCHAR(160),component_type VARCHAR(30),calculation_type VARCHAR(20),calculation_base_code VARCHAR(40),default_value NUMERIC(14,4),taxable BOOLEAN,pf_applicable BOOLEAN,esi_applicable BOOLEAN,prorated BOOLEAN,included_in_gross BOOLEAN,included_in_ctc BOOLEAN,included_in_net BOOLEAN,rounding_scale INT,effective_from DATE,effective_to DATE,status VARCHAR(20),updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(tenant_id,code,effective_from),UNIQUE(id,tenant_id))").update();db.sql("CREATE TABLE salary_structure(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,code VARCHAR(40),name VARCHAR(160),description VARCHAR(500),effective_from DATE,effective_to DATE,status VARCHAR(20),updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(tenant_id,code,effective_from),UNIQUE(id,tenant_id))").update();db.sql("CREATE TABLE salary_structure_component(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,salary_structure_id UUID,salary_component_id UUID,sequence_number INT,component_value NUMERIC(14,4),formula_expression VARCHAR(1000),UNIQUE(tenant_id,salary_structure_id,salary_component_id),UNIQUE(tenant_id,salary_structure_id,sequence_number),FOREIGN KEY(salary_structure_id,tenant_id) REFERENCES salary_structure(id,tenant_id),FOREIGN KEY(salary_component_id,tenant_id) REFERENCES salary_component(id,tenant_id))").update();db.sql("CREATE TABLE employee_salary_assignment(id UUID PRIMARY KEY,tenant_id UUID NOT NULL,employment_id UUID,salary_structure_id UUID,effective_from DATE,effective_to DATE,annual_ctc NUMERIC(14,2),revision_reason VARCHAR(500),created_by VARCHAR(255),created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,UNIQUE(tenant_id,employment_id,effective_from),FOREIGN KEY(employment_id,tenant_id) REFERENCES employment(id,tenant_id),FOREIGN KEY(salary_structure_id,tenant_id) REFERENCES salary_structure(id,tenant_id))").update();}
}
