package com.multitenanterp.leave;

import com.multitenanterp.platform.tenant.TenantContext;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import java.math.BigDecimal;
import java.sql.*;
import java.util.*;

@Service
public class LeaveService {
 private final JdbcClient db;
 public LeaveService(JdbcClient db){this.db=db;}
 public List<LeaveType> types(){return db.sql("SELECT * FROM leave_type WHERE tenant_id=:tenant ORDER BY name").param("tenant",tenant()).query(LeaveService::mapType).list();}
 public LeaveType saveType(UUID id,SaveLeaveTypeRequest r){
  if(r.maximumDays()!=null&&r.maximumDays().compareTo(r.minimumDays())<0)throw bad("Maximum days cannot be less than minimum days");
  boolean create=id==null;id=create?UUID.randomUUID():id;
  try{int count=(create?db.sql("INSERT INTO leave_type(id,tenant_id,code,name,paid,annual_entitlement,accrual_frequency,minimum_days,maximum_days,half_day_allowed,carry_forward_limit,negative_balance_allowed,supporting_document_required,status) VALUES(:id,:tenant,:code,:name,:paid,:annual,:frequency,:minimum,:maximum,:half,:carry,:negative,:document,:status)")
   :db.sql("UPDATE leave_type SET code=:code,name=:name,paid=:paid,annual_entitlement=:annual,accrual_frequency=:frequency,minimum_days=:minimum,maximum_days=:maximum,half_day_allowed=:half,carry_forward_limit=:carry,negative_balance_allowed=:negative,supporting_document_required=:document,status=:status,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND tenant_id=:tenant"))
   .param("id",id).param("tenant",tenant()).param("code",norm(r.code())).param("name",r.name().trim()).param("paid",r.paid()).param("annual",r.annualEntitlement()).param("frequency",norm(r.accrualFrequency())).param("minimum",r.minimumDays()).param("maximum",r.maximumDays()).param("half",r.halfDayAllowed()).param("carry",r.carryForwardLimit()).param("negative",r.negativeBalanceAllowed()).param("document",r.supportingDocumentRequired()).param("status",r.status()==null?"ACTIVE":norm(r.status())).update();
   if(count==0)throw missing("Leave type");
  }catch(DataIntegrityViolationException e){throw conflict("Leave type code or rules are invalid for this company");}
  UUID saved=id;return types().stream().filter(x->x.id().equals(saved)).findFirst().orElseThrow();
 }
 public List<LeaveBalance> balances(UUID employee,Integer year){String extra=employee==null?"":" AND employment_id=:employee";var q=db.sql("SELECT * FROM leave_balance WHERE tenant_id=:tenant"+extra+(year==null?"":" AND leave_year=:year")+" ORDER BY leave_year DESC,employment_id").param("tenant",tenant());if(employee!=null)q.param("employee",employee);if(year!=null)q.param("year",year);return q.query(LeaveService::mapBalance).list();}
 public LeaveBalance saveBalance(SaveLeaveBalanceRequest r){UUID id=db.sql("SELECT id FROM leave_balance WHERE tenant_id=:tenant AND employment_id=:employee AND leave_type_id=:type AND leave_year=:year").param("tenant",tenant()).param("employee",r.employmentId()).param("type",r.leaveTypeId()).param("year",r.leaveYear()).query(UUID.class).optional().orElse(UUID.randomUUID());
  try{db.sql("INSERT INTO leave_balance(id,tenant_id,employment_id,leave_type_id,leave_year,opening_balance,accrued,adjusted) VALUES(:id,:tenant,:employee,:type,:year,:opening,:accrued,:adjusted) ON CONFLICT (tenant_id,employment_id,leave_type_id,leave_year) DO UPDATE SET opening_balance=EXCLUDED.opening_balance,accrued=EXCLUDED.accrued,adjusted=EXCLUDED.adjusted,updated_at=CURRENT_TIMESTAMP").param("id",id).param("tenant",tenant()).param("employee",r.employmentId()).param("type",r.leaveTypeId()).param("year",r.leaveYear()).param("opening",r.openingBalance()).param("accrued",r.accrued()).param("adjusted",r.adjusted()).update();}catch(DataIntegrityViolationException e){throw conflict("Employee or leave type belongs to another company");}
  return balances(r.employmentId(),r.leaveYear()).stream().filter(x->x.leaveTypeId().equals(r.leaveTypeId())).findFirst().orElseThrow();}
 public List<LeaveRequest> requests(UUID employee,String status){String sql="SELECT * FROM leave_request WHERE tenant_id=:tenant"+(employee==null?"":" AND employment_id=:employee")+(status==null?"":" AND status=:status")+" ORDER BY requested_at DESC";var q=db.sql(sql).param("tenant",tenant());if(employee!=null)q.param("employee",employee);if(status!=null)q.param("status",norm(status));return q.query(LeaveService::mapRequest).list();}
 public LeaveRequest request(CreateLeaveRequest r,String actor){if(r.endDate().isBefore(r.startDate()))throw bad("End date cannot precede start date");if(r.startDate().getYear()!=r.endDate().getYear())throw bad("A leave request must be within one leave year");LeaveType type=type(r.leaveTypeId());if(r.requestedDays().compareTo(type.minimumDays())<0||type.maximumDays()!=null&&r.requestedDays().compareTo(type.maximumDays())>0)throw bad("Requested days are outside leave type limits");if(!type.halfDayAllowed()&&hasFraction(r.requestedDays()))throw bad("Half-day leave is not allowed");if(overlap(r))throw conflict("Leave dates overlap an existing pending or approved request");requireBalance(r,type);
  UUID id=UUID.randomUUID();try{db.sql("INSERT INTO leave_request(id,tenant_id,employment_id,leave_type_id,start_date,end_date,requested_days,reason,requested_by) VALUES(:id,:tenant,:employee,:type,:start,:end,:days,:reason,:actor)").param("id",id).param("tenant",tenant()).param("employee",r.employmentId()).param("type",r.leaveTypeId()).param("start",r.startDate()).param("end",r.endDate()).param("days",r.requestedDays()).param("reason",r.reason().trim()).param("actor",actor).update();}catch(DataIntegrityViolationException e){throw conflict("Employee or leave type belongs to another company");}return one(id);}
 @Transactional public LeaveRequest decide(UUID id,DecideLeaveRequest r,String actor){LeaveRequest current=one(id);if(!current.status().equals("PENDING"))throw conflict("Only pending requests can be decided");if(r.decision().equals("APPROVED")){LeaveType type=type(current.leaveTypeId());BigDecimal available=balances(current.employmentId(),current.startDate().getYear()).stream().filter(b->b.leaveTypeId().equals(current.leaveTypeId())).map(LeaveBalance::available).findFirst().orElse(BigDecimal.ZERO);if(!type.negativeBalanceAllowed()&&available.compareTo(current.requestedDays())<0)throw conflict("Insufficient leave balance");int changed=db.sql("UPDATE leave_balance SET used=used+:days,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=:tenant AND employment_id=:employee AND leave_type_id=:type AND leave_year=:year").param("days",current.requestedDays()).param("tenant",tenant()).param("employee",current.employmentId()).param("type",current.leaveTypeId()).param("year",current.startDate().getYear()).update();if(changed==0)throw conflict("Leave balance has not been configured");}
  db.sql("UPDATE leave_request SET status=:status,decided_by=:actor,decided_at=CURRENT_TIMESTAMP,decision_comment=:comment,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND tenant_id=:tenant").param("status",r.decision()).param("actor",actor).param("comment",clean(r.comment())).param("id",id).param("tenant",tenant()).update();return one(id);}
 public LeaveRequest cancel(UUID id,String actor){LeaveRequest current=one(id);if(!current.status().equals("PENDING"))throw conflict("Only pending requests can be cancelled");db.sql("UPDATE leave_request SET status='CANCELLED',decided_by=:actor,decided_at=CURRENT_TIMESTAMP WHERE id=:id AND tenant_id=:tenant").param("actor",actor).param("id",id).param("tenant",tenant()).update();return one(id);}
 private boolean overlap(CreateLeaveRequest r){return db.sql("SELECT COUNT(*) FROM leave_request WHERE tenant_id=:tenant AND employment_id=:employee AND status IN ('PENDING','APPROVED') AND start_date<=:endDate AND end_date>=:startDate").param("tenant",tenant()).param("employee",r.employmentId()).param("startDate",r.startDate()).param("endDate",r.endDate()).query(Integer.class).single()>0;}
 private void requireBalance(CreateLeaveRequest r,LeaveType type){if(type.negativeBalanceAllowed())return;BigDecimal available=balances(r.employmentId(),r.startDate().getYear()).stream().filter(b->b.leaveTypeId().equals(r.leaveTypeId())).map(LeaveBalance::available).findFirst().orElse(BigDecimal.ZERO);BigDecimal pending=db.sql("SELECT COALESCE(SUM(requested_days),0) FROM leave_request WHERE tenant_id=:tenant AND employment_id=:employee AND leave_type_id=:type AND status='PENDING' AND EXTRACT(YEAR FROM start_date)=:year").param("tenant",tenant()).param("employee",r.employmentId()).param("type",r.leaveTypeId()).param("year",r.startDate().getYear()).query(BigDecimal.class).single();if(available.subtract(pending).compareTo(r.requestedDays())<0)throw conflict("Insufficient leave balance");}
 private LeaveType type(UUID id){return types().stream().filter(x->x.id().equals(id)).findFirst().orElseThrow(()->missing("Leave type"));}private LeaveRequest one(UUID id){return db.sql("SELECT * FROM leave_request WHERE id=:id AND tenant_id=:tenant").param("id",id).param("tenant",tenant()).query(LeaveService::mapRequest).optional().orElseThrow(()->missing("Leave request"));}
 private static LeaveType mapType(ResultSet r,int n)throws SQLException{return new LeaveType(r.getObject("id",UUID.class),r.getString("code"),r.getString("name"),r.getBoolean("paid"),r.getBigDecimal("annual_entitlement"),r.getString("accrual_frequency"),r.getBigDecimal("minimum_days"),r.getBigDecimal("maximum_days"),r.getBoolean("half_day_allowed"),r.getBigDecimal("carry_forward_limit"),r.getBoolean("negative_balance_allowed"),r.getBoolean("supporting_document_required"),r.getString("status"));}
 private static LeaveBalance mapBalance(ResultSet r,int n)throws SQLException{BigDecimal opening=r.getBigDecimal("opening_balance"),accrued=r.getBigDecimal("accrued"),adjusted=r.getBigDecimal("adjusted"),used=r.getBigDecimal("used");return new LeaveBalance(r.getObject("id",UUID.class),r.getObject("employment_id",UUID.class),r.getObject("leave_type_id",UUID.class),r.getInt("leave_year"),opening,accrued,adjusted,used,opening.add(accrued).add(adjusted).subtract(used));}
 private static LeaveRequest mapRequest(ResultSet r,int n)throws SQLException{return new LeaveRequest(r.getObject("id",UUID.class),r.getObject("employment_id",UUID.class),r.getObject("leave_type_id",UUID.class),r.getDate("start_date").toLocalDate(),r.getDate("end_date").toLocalDate(),r.getBigDecimal("requested_days"),r.getString("reason"),r.getString("status"),r.getString("requested_by"),r.getTimestamp("requested_at").toInstant(),r.getString("decided_by"),r.getTimestamp("decided_at")==null?null:r.getTimestamp("decided_at").toInstant(),r.getString("decision_comment"));}
 private static boolean hasFraction(BigDecimal v){return v.stripTrailingZeros().scale()>0;}private static UUID tenant(){return TenantContext.requireTenantId();}private static String norm(String v){return v.trim().toUpperCase(Locale.ROOT);}private static String clean(String v){return v==null||v.isBlank()?null:v.trim();}private static ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}private static ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}private static ResponseStatusException missing(String n){return new ResponseStatusException(HttpStatus.NOT_FOUND,n+" not found");}
}
